import { hstPlan } from "./math";

export type GuideNavItem = {
  href: string;
  label: string;
  shortLabel: string;
  description: string;
};

export const GUIDE_NAV: readonly GuideNavItem[] = [
  {
    href: "/app/quilt-guide",
    label: "Workbench",
    shortLabel: "Home",
    description: "Fast answers and guide map",
  },
  {
    href: "/app/quilt-guide/precut-library",
    label: "Precut atlas",
    shortLabel: "Precuts",
    description: "Layer squares, charms, strips, and mixing",
  },
  {
    href: "/app/quilt-guide/triangle-school",
    label: "Triangle school",
    shortLabel: "Triangles",
    description: "HST, QST, and Flying Geese math",
  },
  {
    href: "/app/quilt-guide/block-library",
    label: "Block library",
    shortLabel: "Blocks",
    description: "Named traditional and modern recipes",
  },
  {
    href: "/app/quilt-guide/quilt-planner",
    label: "Quilt planner",
    shortLabel: "Planner",
    description: "Start with a target and skip the math",
  },
  {
    href: "/app/quilt-guide/ruler-cutting",
    label: "Ruler cutting",
    shortLabel: "Cutting",
    description: "Efficient standard and slotted-ruler workflows",
  },
  {
    href: "/app/quilt-guide/finishing",
    label: "Finish the quilt",
    shortLabel: "Finishing",
    description: "Borders, backing, and binding",
  },
  {
    href: "/app/quilt-guide/sources",
    label: "Sources & terms",
    shortLabel: "Sources",
    description: "Research notes, glossary, and caveats",
  },
];

export type Precut = {
  id: "layer" | "charm" | "mini" | "jelly" | "honey" | "fat-quarter" | "fat-eighth";
  genericName: string;
  familiarName: string;
  cut: string;
  directFinish: string;
  modaCount: string;
  description: string;
  color: "tomato" | "gold" | "teal" | "navy" | "lilac" | "pink" | "cream";
};

export const PRECUTS: readonly Precut[] = [
  {
    id: "layer",
    genericName: "10-inch square",
    familiarName: "Layer Cake®",
    cut: "10″ × 10″",
    directFinish: "9½″ square",
    modaCount: "42 pieces",
    description: "Large squares for fast grids, HST batches, QSTs, strips, and subcuts.",
    color: "tomato",
  },
  {
    id: "charm",
    genericName: "5-inch square",
    familiarName: "Charm Pack",
    cut: "5″ × 5″",
    directFinish: "4½″ square",
    modaCount: "42 pieces",
    description: "A versatile patch size for four-patches, HSTs, geese, and scrappy blocks.",
    color: "gold",
  },
  {
    id: "mini",
    genericName: "2½-inch square",
    familiarName: "Mini Charm",
    cut: "2½″ × 2½″",
    directFinish: "2″ square",
    modaCount: "42 pieces",
    description: "Small ready-cut squares that match the cut width of a standard roll strip.",
    color: "teal",
  },
  {
    id: "jelly",
    genericName: "2½-inch WOF strip",
    familiarName: "Jelly Roll®",
    cut: "2½″ × WOF",
    directFinish: "2″ finished width",
    modaCount: "40 strips",
    description: "Strip sets, rails, logs, bindings, sashing, and fast crosscut squares.",
    color: "navy",
  },
  {
    id: "honey",
    genericName: "1½-inch WOF strip",
    familiarName: "Honey Bun",
    cut: "1½″ × WOF",
    directFinish: "1″ finished width",
    modaCount: "40 strips",
    description: "Narrow logs, tiny rails, accent bands, and one-inch finished sashing.",
    color: "lilac",
  },
  {
    id: "fat-quarter",
    genericName: "Fat quarter",
    familiarName: "Fat Quarter",
    cut: "about 18″ × 21″",
    directFinish: "Cut as needed",
    modaCount: "Varies by collection",
    description: "A wide quarter-yard cut that handles larger patches better than a long quarter.",
    color: "pink",
  },
  {
    id: "fat-eighth",
    genericName: "Fat eighth",
    familiarName: "Fat Eighth",
    cut: "about 9″ × 21″",
    directFinish: "Cut as needed",
    modaCount: "Varies by collection",
    description: "A compact sampler cut for blocks, small runs, and controlled scrappiness.",
    color: "cream",
  },
];

export type BlockCutGroup = {
  fabric: string;
  color: "feature" | "background" | "accent" | "scrap";
  cuts: readonly string[];
};

export type QuiltBlock = {
  slug: string;
  name: string;
  family: "traditional" | "modern";
  finishedSize: string;
  unfinishedSize: string;
  difficulty: "Beginner" | "Confident beginner" | "Intermediate";
  unitType: string;
  summary: string;
  diagram: string;
  cuts: readonly BlockCutGroup[];
  steps: readonly {
    title: string;
    instruction: string;
    checkpoint: string;
  }[];
  precutNote: string;
  accuracyNote: string;
};

const bg = (cuts: readonly string[]): BlockCutGroup => ({
  fabric: "Background",
  color: "background",
  cuts,
});
const feature = (cuts: readonly string[]): BlockCutGroup => ({
  fabric: "Feature",
  color: "feature",
  cuts,
});
const accent = (cuts: readonly string[]): BlockCutGroup => ({
  fabric: "Accent",
  color: "accent",
  cuts,
});
const scraps = (cuts: readonly string[]): BlockCutGroup => ({
  fabric: "Assorted scraps",
  color: "scrap",
  cuts,
});

export const QUILT_BLOCKS: readonly QuiltBlock[] = [
  {
    slug: "four-patch",
    name: "Four Patch",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "Plain squares",
    summary: "The essential two-by-two checkerboard and a clean first lesson in seam nesting.",
    diagram: "four-patch",
    cuts: [feature(["2 — 6½″ squares"]), bg(["2 — 6½″ squares"])],
    steps: [
      { title: "Pair", instruction: "Place one feature and one background square right sides together. Sew one side at a scant ¼″. Repeat with the second pair.", checkpoint: "Each pair is 6½″ × 12½″ raw." },
      { title: "Press opposite", instruction: "Press one pair toward the feature and the other toward the background so the center seams will nest.", checkpoint: "Both pairs stay flat and square." },
      { title: "Nest", instruction: "Rotate one pair. Nest the center seams and pin at the match point.", checkpoint: "Alternating colors form a checkerboard." },
      { title: "Join", instruction: "Sew the long center seam, press, and square only if needed.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Cut 6½″ squares from yardage or a 10″ square. A full charm is too small for this 12″ version.",
    accuracyNote: "The center intersection is the visual target; nesting opposing seam allowances makes it reliable.",
  },
  {
    slug: "nine-patch",
    name: "Nine Patch",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "3 × 3 grid",
    summary: "Nine equal patches arranged in three rows—the foundation of dozens of named blocks.",
    diagram: "nine-patch",
    cuts: [feature(["5 — 4½″ squares"]), bg(["4 — 4½″ squares"])],
    steps: [
      { title: "Lay out", instruction: "Arrange three rows of three, alternating feature and background squares with feature at center.", checkpoint: "Each row contains three 4½″ squares." },
      { title: "Chain-piece", instruction: "Sew the first two columns in each row, then add the third column without clipping threads between rows.", checkpoint: "Three row units measure 4½″ × 12½″." },
      { title: "Press", instruction: "Press row 1 and 3 seams toward the feature; press row 2 the opposite way.", checkpoint: "Adjacent row seams nest." },
      { title: "Join rows", instruction: "Match, pin, and sew the two horizontal seams. Press the final block flat.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Trim nine 5″ charms to 4½″ for a precut-perfect version.",
    accuracyNote: "Measure each row before joining; it should be exactly 12½″ long.",
  },
  {
    slug: "sixteen-patch",
    name: "Sixteen Patch",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "4 × 4 grid",
    summary: "A rhythmic checkerboard with smaller scale and excellent strip-piecing potential.",
    diagram: "sixteen-patch",
    cuts: [feature(["8 — 3½″ squares"]), bg(["8 — 3½″ squares"])],
    steps: [
      { title: "Make pairs", instruction: "Sew feature and background squares into eight alternating pairs.", checkpoint: "Each pair is 3½″ × 6½″ raw." },
      { title: "Build rows", instruction: "Join two pairs per row, reversing every other pair to maintain the checkerboard.", checkpoint: "Four rows measure 3½″ × 12½″." },
      { title: "Press for nesting", instruction: "Press odd rows one direction and even rows the opposite direction.", checkpoint: "All vertical seams nest between rows." },
      { title: "Join four rows", instruction: "Sew rows in order, pinning at every match point. Press the block.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "A 10″ square yields four 3½″ squares with useful leftovers; strip piecing is faster for multiples.",
    accuracyNote: "Tiny errors repeat across four columns, so verify the first row before chain-piecing the rest.",
  },
  {
    slug: "rail-fence",
    name: "Rail Fence",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "Jelly-roll strip set",
    summary: "Three-strip rails rotated by quarter turns for movement with almost no fussy piecing.",
    diagram: "rail-fence",
    cuts: [feature(["4 — 2½″ × 6½″ rectangles"]), accent(["4 — 2½″ × 6½″ rectangles"]), bg(["4 — 2½″ × 6½″ rectangles"])],
    steps: [
      { title: "Build rails", instruction: "Sew one feature, accent, and background rectangle together along the 6½″ edges. Make four matching rail units.", checkpoint: "Each rail is 6½″ square raw." },
      { title: "Press consistently", instruction: "Press both seams toward the darkest strip, keeping the strip set straight rather than bowed.", checkpoint: "Each finished strip shows 2″ wide." },
      { title: "Rotate", instruction: "Arrange the four rail units in a two-by-two grid, turning each unit 90° around the center.", checkpoint: "Rails make a clockwise woven path." },
      { title: "Join", instruction: "Sew into two rows, then join the rows with the center seam nested.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Use three Jelly Roll strips; sew full WOF strip sets and crosscut at the measured 6½″ raw width for multiples.",
    accuracyNote: "Alternate the direction you sew long strip sets to reduce bowing.",
  },
  {
    slug: "log-cabin",
    name: "Log Cabin",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Sequential logs",
    summary: "A classic center square wrapped clockwise with light and dark logs.",
    diagram: "log-cabin",
    cuts: [accent(["1 — 4½″ center square"]), feature(["4 — 2½″ logs: 4½″, 6½″, 8½″, 10½″ long"]), bg(["4 — 2½″ logs: 6½″, 8½″, 10½″, 12½″ long"])],
    steps: [
      { title: "Start the center", instruction: "Sew the 2½″ × 4½″ first log to the right of the 4½″ center. Press away from center.", checkpoint: "Unit is 4½″ × 6½″ raw." },
      { title: "Complete round one", instruction: "Add the 6½″ bottom log, then the 6½″ left log, then the 8½″ top log, pressing after each seam.", checkpoint: "Unit is 8½″ square raw." },
      { title: "Add round two", instruction: "Continue clockwise with 8½″ right, 10½″ bottom, 10½″ left, and 12½″ top logs.", checkpoint: "Every log lies flat with no pulled corner." },
      { title: "Square", instruction: "Check the center remains square and trim only the outermost thread-width irregularities.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "All logs are Jelly Roll width. A single roll gives coordinated light/dark options for many blocks.",
    accuracyNote: "Check after every two logs; a small early error grows through every later round.",
  },
  {
    slug: "courthouse-steps",
    name: "Courthouse Steps",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Paired opposite logs",
    summary: "A Log Cabin relative built in symmetrical pairs on opposite sides of the center.",
    diagram: "courthouse-steps",
    cuts: [accent(["1 — 4½″ center square"]), feature(["2 — 2½″ × 4½″", "2 — 2½″ × 8½″"]), bg(["2 — 2½″ × 8½″", "2 — 2½″ × 12½″"])],
    steps: [
      { title: "Side pair", instruction: "Add 2½″ × 4½″ feature logs to the left and right of the center. Press outward.", checkpoint: "Unit is 4½″ × 8½″." },
      { title: "Top/bottom pair", instruction: "Add 2½″ × 8½″ background logs to top and bottom.", checkpoint: "Unit is 8½″ square." },
      { title: "Repeat outward", instruction: "Add the 2½″ × 8½″ feature side pair, then the 2½″ × 12½″ background top/bottom pair.", checkpoint: "Opposite logs mirror one another." },
      { title: "Final check", instruction: "Press from the center outward and square the outside edge if needed.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Every log is 2½″ wide, so Jelly Roll strips work without width trimming.",
    accuracyNote: "Center each opposite log pair so the block grows symmetrically.",
  },
  {
    slug: "pinwheel",
    name: "Pinwheel",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Four HSTs",
    summary: "Four large half-square triangles spin around one crisp center point.",
    diagram: "pinwheel",
    cuts: [feature(["2 — 7″ squares for HSTs"]), bg(["2 — 7″ squares for HSTs"])],
    steps: [
      { title: "Mark", instruction: "Draw one diagonal on the wrong side of both background squares. Pair each with a feature square, right sides together.", checkpoint: "Two layered square pairs." },
      { title: "Sew and split", instruction: "Sew ¼″ on both sides of each line, cut on the lines, then press toward the feature.", checkpoint: "Four oversized HSTs." },
      { title: "Trim and spin", instruction: "Trim every HST to 6½″, aligning the ruler’s 45° line with the seam. Arrange the feature triangles in a pinwheel.", checkpoint: "Four 6½″ units." },
      { title: "Join", instruction: "Sew two rows, then join through the center with seams nested or fanned.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "This size needs yardage. For a larger 18″-finished pinwheel, use two contrasting pairs of 10″ squares—four squares total—and trim the four HSTs to 9½″.",
    accuracyNote: "Preserve the ¼″ seam allowance beyond the center tips when trimming.",
  },
  {
    slug: "friendship-star",
    name: "Friendship Star",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "HST star",
    summary: "A five-patch star whose four HST points orbit a contrasting center.",
    diagram: "friendship-star",
    cuts: [feature(["1 — 4½″ center", "2 — 5″ HST squares"]), bg(["4 — 4½″ corners", "2 — 5″ HST squares"])],
    steps: [
      { title: "Make HSTs", instruction: "Use the four 5″ squares to make four HSTs two at a time. Press and trim each to 4½″.", checkpoint: "Four 4″-finished HSTs." },
      { title: "Lay out the star", instruction: "Place the feature square at center, plain backgrounds at corners, and HSTs at the four side positions.", checkpoint: "All feature triangles spin the same direction." },
      { title: "Sew rows", instruction: "Join each row of three. Press the middle row away from center and outer rows toward center.", checkpoint: "Three 4½″ × 12½″ rows." },
      { title: "Assemble", instruction: "Nest row seams, sew, and press the complete star.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Trim 5″ charms only after making the HSTs; four extra charms can become the plain corners.",
    accuracyNote: "Either clockwise or counterclockwise spin is valid—keep all four points consistent.",
  },
  {
    slug: "shoo-fly",
    name: "Shoo Fly",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "HST corners",
    summary: "A sturdy nine-patch variation with feature triangles pointing into a square center.",
    diagram: "shoo-fly",
    cuts: [feature(["1 — 4½″ center", "2 — 5″ HST squares"]), bg(["4 — 4½″ side squares", "2 — 5″ HST squares"])],
    steps: [
      { title: "Make HSTs", instruction: "Pair the 5″ squares and make four two-at-a-time HSTs. Trim to 4½″.", checkpoint: "Four identical corner units." },
      { title: "Aim inward", instruction: "Set HSTs in the four corners with every feature triangle touching the feature center diagonally. Fill side positions with background.", checkpoint: "Feature makes a broad X shape." },
      { title: "Join rows", instruction: "Sew three rows, pressing adjacent rows in opposite directions.", checkpoint: "Row seams will nest." },
      { title: "Finish", instruction: "Join rows and press. Check that no corner point is closer than ¼″ to the raw edge.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Charm squares work for every patch; trim plain charms to 4½″ and HSTs after piecing.",
    accuracyNote: "Orientation distinguishes Shoo Fly from other star-like nine patches; point feature triangles inward.",
  },
  {
    slug: "hourglass-quartet",
    name: "Hourglass Quartet",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Intermediate",
    unitType: "Four QSTs",
    summary: "Four oversized hourglass units meet in a graphic burst of quarter-square triangles.",
    diagram: "hourglass-quartet",
    cuts: [feature(["2 — 7½″ QST squares"]), bg(["2 — 7½″ QST squares"])],
    steps: [
      { title: "First diagonal", instruction: "Pair one feature and one background square. Make two HSTs, pressing both seams the same direction. Repeat.", checkpoint: "Four oversized HSTs." },
      { title: "Opposite diagonal", instruction: "Pair HSTs right sides together with opposite colors touching and seams nested. Mark across the unsewn diagonal, sew both sides, and cut.", checkpoint: "Four hourglass units." },
      { title: "Trim", instruction: "Align the ruler center and both 45° diagonals; trim each QST to 6½″.", checkpoint: "Center intersection stays at 3¼″." },
      { title: "Join quartet", instruction: "Arrange the hourglasses in a two-by-two rotation and assemble like a Four Patch.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "This size requires 7½″ squares; 10″ layer squares leave generous room and can be trimmed first.",
    accuracyNote: "Trim equally from all four sides so the center remains centered.",
  },
  {
    slug: "ohio-star",
    name: "Ohio Star",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Intermediate",
    unitType: "QST star points",
    summary: "A canonical nine-patch star with four hourglass point units and calm square corners.",
    diagram: "ohio-star",
    cuts: [feature(["1 — 4½″ center", "2 — 5½″ QST squares"]), bg(["4 — 4½″ corners", "2 — 5½″ QST squares"])],
    steps: [
      { title: "Make QSTs", instruction: "Use the 5½″ squares to make four trim-friendly hourglass units through two diagonal sewing passes.", checkpoint: "Four QSTs ready to trim." },
      { title: "Trim points", instruction: "Square every QST to 4½″ with the center at 2¼″ and diagonal seams running corner to corner.", checkpoint: "Points keep a ¼″ allowance." },
      { title: "Lay out", instruction: "Place the feature square in the center, background squares at corners, and QSTs at the side positions with feature points facing outward.", checkpoint: "A clear eight-point star appears." },
      { title: "Sew 3 × 3", instruction: "Join rows, press for nesting, then join the three rows.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Layer squares are an easy source, but each 10″ square yields only one 5½″ start. You need four 10″ squares total—two feature and two background.",
    accuracyNote: "The QST center is the trimming anchor; do not trim by outer edges alone.",
  },
  {
    slug: "churn-dash",
    name: "Churn Dash",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "HST corners + bar units",
    summary: "A beloved frame-like block combining corner triangles, side bars, and a quiet center.",
    diagram: "churn-dash",
    cuts: [feature(["2 — 5″ HST squares", "4 — 2½″ × 4½″ bars"]), bg(["2 — 5″ HST squares", "4 — 2½″ × 4½″ bars", "1 — 4½″ center"])],
    steps: [
      { title: "Make corners", instruction: "Make four HSTs from the 5″ squares and trim each to 4½″.", checkpoint: "Four 4″-finished corner units." },
      { title: "Make bars", instruction: "Pair each feature bar with a background bar along the 4½″ edge. Press toward feature.", checkpoint: "Four 4½″ square bar units." },
      { title: "Arrange", instruction: "Place HSTs at corners with feature triangles toward center, bar units at sides with feature bars inward, and background at center.", checkpoint: "Feature fabric forms the dash frame." },
      { title: "Join", instruction: "Sew the nine units as three rows, then join rows with seams nested.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Use charms for HST starts; Jelly Roll strips supply the 2½″ bars efficiently.",
    accuracyNote: "Check bar-unit orientation before sewing rows—the feature bars all face the center.",
  },
  {
    slug: "sawtooth-star",
    name: "Sawtooth Star",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Four Flying Geese",
    summary: "The classic eight-point star built around a generous center square.",
    diagram: "sawtooth-star",
    cuts: [feature(["1 — 6½″ center", "4 — 3½″ × 6½″ goose bodies"]), bg(["4 — 3½″ corner squares", "8 — 3½″ sky squares"])],
    steps: [
      { title: "First goose wing", instruction: "Mark a diagonal on each sky square. Place one on a goose body end, sew on the line, trim the outer corner ¼″ beyond the seam, and press open.", checkpoint: "Feature body still fills the opposite end." },
      { title: "Second wing", instruction: "Repeat on the other end with a second sky square. Make four geese total.", checkpoint: "Each goose is 3½″ × 6½″ with a ¼″ point allowance." },
      { title: "Build rows", instruction: "Join a background corner to each end of the top and bottom geese. Join side geese to the center square.", checkpoint: "Three rows are 12½″ wide." },
      { title: "Join star", instruction: "Match goose points and row seams, sew the rows together, and press.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "One 10″ square supplies the center; two more can yield the four 3½″ × 6½″ bodies. Charms can supply the 3½″ sky squares. A 2½″ strip is too narrow for this recipe.",
    accuracyNote: "Keep the goose tip ¼″ below its raw edge so the final star points do not disappear.",
  },
  {
    slug: "dutchmans-puzzle",
    name: "Dutchman’s Puzzle",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Intermediate",
    unitType: "Eight Flying Geese",
    summary: "Pairs of geese sweep around the center in a bold rotating puzzle.",
    diagram: "dutchmans-puzzle",
    cuts: [feature(["4 — 3½″ × 6½″ goose bodies"]), accent(["4 — 3½″ × 6½″ goose bodies"]), bg(["16 — 3½″ sky squares"])],
    steps: [
      { title: "Make eight geese", instruction: "Use stitch-and-flip sky squares on both ends of every body rectangle. Make four geese in each feature color.", checkpoint: "Eight geese at 3½″ × 6½″." },
      { title: "Pair colors", instruction: "Stack one feature goose and one accent goose along their long edges, both pointing the same direction. Make four quadrants.", checkpoint: "Four 6½″ squares." },
      { title: "Rotate quadrants", instruction: "Arrange the four paired quadrants so their points circle clockwise around the block center.", checkpoint: "No pair points outward from the center." },
      { title: "Assemble", instruction: "Join quadrants in two rows, then sew the center seam.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Layer squares can be subcut for bodies and charms for sky squares; verify directional prints before flipping corners.",
    accuracyNote: "Make one test goose and confirm 3½″ × 6½″ before chain-piecing the remaining seven.",
  },
  {
    slug: "jacobs-ladder",
    name: "Jacob’s Ladder",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Five Four Patches + four HSTs",
    summary: "A diagonal chain emerges from alternating Four Patches and half-square triangles.",
    diagram: "jacobs-ladder",
    cuts: [feature(["10 — 2½″ squares", "2 — 5″ HST squares"]), bg(["10 — 2½″ squares", "2 — 5″ HST squares"])],
    steps: [
      { title: "Five Four Patches", instruction: "Pair 2½″ feature and background squares, press in opposite directions, then join pairs into five checkerboard Four Patches.", checkpoint: "Five units trim to 4½″." },
      { title: "Four HSTs", instruction: "Use the 5″ squares to make four two-at-a-time HSTs. Trim to 4½″.", checkpoint: "Nine total 4½″ subunits." },
      { title: "Build the ladder", instruction: "Place Four Patches at all four corners and center. Fill side positions with HSTs so feature triangles continue one diagonal chain.", checkpoint: "The feature path runs corner to corner." },
      { title: "Join rows", instruction: "Sew the 3 × 3 grid, nesting seams where possible.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Mini charms are ready for the Four Patches; charms make the HSTs with trimming room.",
    accuracyNote: "Rotate the center Four Patch to continue the same diagonal color path.",
  },
  {
    slug: "snowball",
    name: "Snowball",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "Stitch-and-flip corners",
    summary: "A broad feature square with clipped corners; this recipe declares a one-third corner proportion.",
    diagram: "snowball",
    cuts: [feature(["1 — 12½″ square"]), bg(["4 — 4½″ corner squares"])],
    steps: [
      { title: "Mark corners", instruction: "Draw one diagonal on the wrong side of all four 4½″ background squares.", checkpoint: "Lines run corner to corner." },
      { title: "Sew", instruction: "Place one marked square at each feature-square corner, right sides together, and sew on every line.", checkpoint: "Marked triangles point toward the large square center." },
      { title: "Trim and press", instruction: "Trim ¼″ outside each seam, removing the outer corner layers. Press sky triangles outward.", checkpoint: "Block remains 12½″ square." },
      { title: "Check the frame", instruction: "Square the raw outer edge and confirm feature points stop ¼″ before each corner seam.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "A Layer Cake makes a smaller 9½″-finished Snowball; scale corners to the declared ratio or follow that pattern’s exact recipe.",
    accuracyNote: "Snowball proportions vary by pattern; this page intentionally uses 4″-finished corner triangles.",
  },
  {
    slug: "bear-paw",
    name: "Bear Paw",
    family: "traditional",
    finishedSize: "14″",
    unfinishedSize: "14½″",
    difficulty: "Intermediate",
    unitType: "Four paw quadrants + sashing",
    summary: "Four clawed paws gather around a narrow center sashing cross.",
    diagram: "bear-paw",
    cuts: [feature(["4 — 4½″ paw pads", "8 — 3″ HST squares"]), bg(["8 — 3″ HST squares", "4 — 2½″ quadrant corners", "4 — 2½″ × 6½″ sashing bars", "1 — 2½″ center square"])],
    steps: [
      { title: "Make claws", instruction: "Pair the sixteen 3″ starts to make sixteen HSTs two at a time. Trim every claw to 2½″.", checkpoint: "Sixteen 2″-finished HSTs." },
      { title: "Build four paws", instruction: "For each paw, join two HSTs above the 4½″ pad and two beside it; add one 2½″ background corner to complete a 6½″ quadrant.", checkpoint: "Four paw quadrants at 6½″." },
      { title: "Add sashing", instruction: "Join a 2½″ × 6½″ sashing bar between each pair of paws. Make the middle row from bar, center square, bar.", checkpoint: "Three rows measure 14½″ wide." },
      { title: "Join rows", instruction: "Sew the three rows, matching the sashing cross and keeping all claws pointed away from their pad.", checkpoint: "14½″ raw / 14″ finished." },
    ],
    precutNote: "Mini charms can become claw HSTs only in a smaller variant; this 14″ recipe starts at 3″ for trimming accuracy.",
    accuracyNote: "Bear Paw layouts vary. This is the traditional seven-grid, four-paw variant with a 2″ finished sashing cross.",
  },
  {
    slug: "disappearing-nine-patch",
    name: "Disappearing Nine Patch",
    family: "traditional",
    finishedSize: "13″",
    unfinishedSize: "13½″",
    difficulty: "Confident beginner",
    unitType: "Cut-and-rearrange Nine Patch",
    summary: "A sewn Nine Patch is quartered, rotated, and resewn into a surprisingly complex grid.",
    diagram: "disappearing-nine-patch",
    cuts: [scraps(["9 — 5″ charm squares"])],
    steps: [
      { title: "Make a Nine Patch", instruction: "Arrange and sew nine 5″ charms as three rows of three. Press for nesting.", checkpoint: "The first block measures 14″ raw." },
      { title: "Quarter it", instruction: "Measure 7″ from either raw edge and cut vertically through center. Without shifting, cut horizontally at 7″.", checkpoint: "Four 7″ square quarters." },
      { title: "Rearrange", instruction: "Rotate two opposite quarters 180°, or swap quarters, keeping all four raw squares in a two-by-two layout.", checkpoint: "Small center patches move to new positions." },
      { title: "Resew", instruction: "Join the four quarters like a Four Patch and press.", checkpoint: "13½″ raw / 13″ finished." },
    ],
    precutNote: "This version is designed specifically for nine untrimmed 5″ charm squares.",
    accuracyNote: "The general finished-size formula for this version is three times the starting square minus 2″.",
  },
  {
    slug: "modern-plus",
    name: "Modern Plus",
    family: "modern",
    finishedSize: "10″",
    unfinishedSize: "10½″",
    difficulty: "Beginner",
    unitType: "5 × 5 mini grid",
    summary: "A crisp plus sign drawn through a field of small squares with bold negative space.",
    diagram: "modern-plus",
    cuts: [feature(["9 — 2½″ squares"]), bg(["16 — 2½″ squares"])],
    steps: [
      { title: "Map the plus", instruction: "Lay out a 5 × 5 grid with feature squares filling the complete center row and center column.", checkpoint: "Nine feature squares form one continuous plus." },
      { title: "Sew rows", instruction: "Chain-piece five rows, keeping each row attached by thread in order.", checkpoint: "Five rows at 2½″ × 10½″." },
      { title: "Press alternating", instruction: "Press odd rows left and even rows right so every vertical seam nests.", checkpoint: "Grid intersections align." },
      { title: "Join", instruction: "Sew the five rows and press the block flat.", checkpoint: "10½″ raw / 10″ finished." },
    ],
    precutNote: "Mini charms are exactly the required cut size—nine feature and sixteen background.",
    accuracyNote: "Keep background values quiet so the plus retains a strong silhouette.",
  },
  {
    slug: "hst-chevron",
    name: "HST Chevron",
    family: "modern",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "16 HSTs",
    summary: "Sixteen small HSTs repeat into a clean zigzag with strong directional energy.",
    diagram: "hst-chevron",
    cuts: [feature(["8 — 4″ HST squares"]), bg(["8 — 4″ HST squares"])],
    steps: [
      { title: "Batch HSTs", instruction: "Use the sixteen 4″ squares to make sixteen HSTs two at a time.", checkpoint: "Eight paired batches yield sixteen." },
      { title: "Trim", instruction: "Trim each HST to 3½″ with the 45° seam on the ruler diagonal.", checkpoint: "Sixteen 3″-finished HSTs." },
      { title: "Make chevrons", instruction: "Arrange a 4 × 4 grid. Mirror adjacent HST diagonals to create repeated V shapes across each row.", checkpoint: "All V shapes point the same direction." },
      { title: "Assemble grid", instruction: "Join rows, pressing alternating directions, then join all four rows.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Charm squares are ideal HST starts: sew first, then trim the finished units to 3½″.",
    accuracyNote: "Photograph the layout before sewing; one rotated HST breaks the entire chevron rhythm.",
  },
  {
    slug: "wonky-star",
    name: "Wonky Star",
    family: "modern",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Improvised star-point wedges",
    summary: "An intentionally irregular nine-patch star with lively, individually angled points.",
    diagram: "wonky-star",
    cuts: [feature(["1 — 4½″ center square"]), bg(["8 — 4½″ squares"]), scraps(["8 wedges, each at least 3″ × 5″"])],
    steps: [
      { title: "First point", instruction: "Lay one scrap wedge diagonally across a background square, right sides together. Sew, flip, and confirm it covers a corner; trim the hidden layers.", checkpoint: "Feature wedge reaches one raw edge." },
      { title: "Second point", instruction: "Add a contrasting wedge from the adjacent side. Press and trim the entire point unit back to 4½″. Make four varied units.", checkpoint: "Four side units, each with two wonky points." },
      { title: "Arrange", instruction: "Place the feature square at center, point units at the four sides, and untouched background squares at corners.", checkpoint: "Eight irregular points surround center." },
      { title: "Join nine-patch", instruction: "Sew three rows, then join rows. Preserve ¼″ beyond the innermost point tips.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Use charms trimmed to 4½″ for background and leftovers for the improvised wedges.",
    accuracyNote: "Wonky means varied angles, not missing seam allowance; every finished point still needs room beyond its tip.",
  },
  {
    slug: "offset-log-cabin",
    name: "Offset Log Cabin",
    family: "modern",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Color-shifted logs",
    summary: "Classic Log Cabin construction pushed off balance by concentrated color and asymmetric value.",
    diagram: "offset-log-cabin",
    cuts: [accent(["1 — 4½″ center square"]), feature(["4 — 2½″ logs: 4½″, 6½″, 8½″, 10½″ long"]), bg(["4 — 2½″ logs: 6½″, 8½″, 10½″, 12½″ long"])],
    steps: [
      { title: "Choose the pull", instruction: "Place saturated feature logs on the right and bottom path; reserve low-volume logs for the opposite path.", checkpoint: "Value plan creates the visual offset." },
      { title: "Round one", instruction: "Add 4½″, 6½″, 6½″, and 8½″ logs clockwise, pressing outward.", checkpoint: "8½″ square after four logs." },
      { title: "Round two", instruction: "Continue with 8½″, 10½″, 10½″, and 12½″ logs, preserving the high/low value split.", checkpoint: "12½″ square after eight logs." },
      { title: "Compose multiples", instruction: "Rotate completed blocks independently to create a larger off-center ripple.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Jelly Roll strips supply every log; sort them into strong and quiet value groups before cutting lengths.",
    accuracyNote: "The geometry is square; the offset comes from color placement, so value contrast matters more than print family.",
  },
  {
    slug: "stacked-coins",
    name: "Stacked Coins",
    family: "modern",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "Pieced coin columns",
    summary: "Two columns of short fabric ‘coins’ float between slim bands of negative space.",
    diagram: "stacked-coins",
    cuts: [scraps(["8 — 4½″ × 3½″ coin rectangles"]), bg(["1 — 2½″ × 12½″ center strip", "2 — 1½″ × 12½″ outer strips"])],
    steps: [
      { title: "Stack coins", instruction: "Divide coin rectangles into two sets of four. Sew each set end to end along 4½″ edges.", checkpoint: "Two columns at 4½″ × 12½″." },
      { title: "Press the stacks", instruction: "Press coin seams in alternating directions or open to keep bulky intersections flat.", checkpoint: "Both columns remain straight." },
      { title: "Insert negative space", instruction: "Sew the 2½″ center strip between coin columns. Add a 1½″ strip to each outside edge.", checkpoint: "Full unit is 12½″ wide." },
      { title: "Square", instruction: "Align a long ruler with the center strip and trim the top/bottom only if necessary.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Charm squares can be trimmed to 4½″ × 3½″ coins; directional prints should all face the same way before stacking.",
    accuracyNote: "Measure each coin column before adding sashing; both must finish at the same 12½″ raw height.",
  },
  {
    slug: "minimalist-cross",
    name: "Minimalist Cross",
    family: "modern",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "Narrow cross in a 3 × 3 layout",
    summary: "A slim two-inch-finished cross divides four oversized fields of negative space.",
    diagram: "minimalist-cross",
    cuts: [feature(["1 — 2½″ center", "2 — 2½″ × 5½″ vertical arms", "2 — 5½″ × 2½″ horizontal arms"]), bg(["4 — 5½″ squares"])],
    steps: [
      { title: "Build three rows", instruction: "Top and bottom rows are background square, vertical arm, background square. The middle row is horizontal arm, center, horizontal arm.", checkpoint: "Rows are 5½″, 2½″, and 5½″ high." },
      { title: "Join row pieces", instruction: "Sew within each row and press all seams toward the feature cross.", checkpoint: "Every row measures 12½″ wide." },
      { title: "Match center lines", instruction: "Mark or finger-press each row midpoint and align the vertical arm through all three rows.", checkpoint: "Cross is continuous and centered." },
      { title: "Sew rows", instruction: "Join top, middle, and bottom rows; press toward the narrow middle row.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Jelly Roll strips provide every cross piece; layer squares can yield the 5½″ background fields.",
    accuracyNote: "Because the background is quiet, a wandering vertical alignment is visible—match the arm edges, not just raw corners.",
  },
  {
    slug: "improv-mosaic",
    name: "Improv Mosaic",
    family: "modern",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Intermediate",
    unitType: "Improvisational slabs",
    summary: "Scrap-built slabs are trimmed into controlled quadrants, balancing spontaneity with a reliable final size.",
    diagram: "improv-mosaic",
    cuts: [scraps(["Strips and chunks 1½″–3½″ wide", "Enough to cover four 7″ squares"]), bg(["Optional narrow contrast strips 1″–1½″ wide"])],
    steps: [
      { title: "Build slabs", instruction: "Join scraps into small pairs, then join pairs into four loose slabs at least 7″ square. Vary line lengths and avoid lining up every seam.", checkpoint: "Four slabs cover a 7″ square ruler area." },
      { title: "Press and trim", instruction: "Press each new seam before adding the next piece. Trim four slabs to exactly 6½″ square.", checkpoint: "Four stable, square quadrants." },
      { title: "Rotate for balance", instruction: "Turn quadrants until color, scale, and seam direction feel distributed. Keep bulky intersections away from the center when possible.", checkpoint: "A balanced 2 × 2 mosaic." },
      { title: "Join", instruction: "Assemble like a Four Patch. Press the center seam open to reduce bulk.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Use orphan mini charms, Jelly Roll ends, and trimming leftovers; this is the intentional scrap-release valve.",
    accuracyNote: "The interior is improvised, but the four 6½″ trimmed quadrants make the final size deterministic.",
  },
];

export function getBlock(slug: string) {
  return QUILT_BLOCKS.find((block) => block.slug === slug);
}

export const RESEARCH_SOURCES = [
  {
    title: "Moda — Precut customer guide",
    url: "https://webfiles.modafabrics.com/webfiles/moda-customer-packet.pdf",
    use: "Moda-specific names, nominal sizes, and typical pack counts.",
  },
  {
    title: "Moda — Precut 411",
    url: "https://my.modafabrics.com/inspiration-resources/precut-411",
    use: "Manufacturer and package-count variability.",
  },
  {
    title: "Moda — Jelly, Honey & Accuracy",
    url: "https://modafabrics.com/inspiration-resources/jelly-honey-accuracy",
    use: "Pinked-edge alignment and scant-quarter-inch handling for Moda strips.",
  },
  {
    title: "BERNINA WeAllSew — Accurate Piecing Basics",
    url: "https://weallsew.com/accurate-piecing-basics-quarter-inch-seams/",
    use: "Scant ¼″ explanation and seam-accuracy test.",
  },
  {
    title: "Moda — Half-Triangle Squares Revisited",
    url: "https://my.modafabrics.com/2018/03/tip-jar-half-triangle-squares-revisited",
    use: "Traditional two-at-a-time HST formula.",
  },
  {
    title: "Quilting Daily / OLFA — Eight-at-a-time HSTs",
    url: "https://www.quiltingdaily.com/wp-content/uploads/2018/08/Olfa-Schoolhouse-Steps-Complete.pdf",
    use: "Magic 8 formula and cutting sequence.",
  },
  {
    title: "Moda — Quarter-Square Triangles",
    url: "https://www.modafabrics.com/2018/09/building-blocks-quarter-square-triangles.html",
    use: "QST sizing, yield, and trim-friendly allowance.",
  },
  {
    title: "Moda — Four-from-one Flying Geese",
    url: "https://my.modafabrics.com/2018/09/building-blocks-4-from-1-flying-geese.html",
    use: "No-waste Flying Geese formulas and precut combinations.",
  },
  {
    title: "AllPeopleQuilt — Backing yardage",
    url: "https://www.allpeoplequilt.com/how-to-quilt/finishing/plan-your-quilt-back-and-determine-yardage",
    use: "Backing margin, seams, and orientation planning.",
  },
  {
    title: "Moda — Binding Basics",
    url: "https://my.modafabrics.com/inspiration-resources/binding-basics",
    use: "Usable WOF, strip count, and binding yardage workflow.",
  },
  {
    title: "GE Designs — Stripology® XL CGRGE1XL",
    url: "https://gequiltdesigns.com/products/stripology-xl-ruler-by-ge-designs",
    use: "Creator specifications, capacity, dimensions, and supported cutting jobs for Scott’s slotted ruler.",
  },
  {
    title: "GE Designs — Stripology 101",
    url: "https://gequiltdesigns.com/pages/stripology-101-video-tutorials",
    use: "Creator-led ruler setup, folding, cutting, and subcutting guidance.",
  },
  {
    title: "Creative Grids — 6½″ × 12½″ rectangle CGR612",
    url: "https://www.creativegridsusa.com/products/CGR612",
    use: "Official markings, Turn-a-Round edges, angle lines, and trimming uses for Scott’s bench ruler.",
  },
  {
    title: "Fiskars — 6″ × 24″ sewing ruler 1066148",
    url: "https://www.amazon.com/dp/B0C8BMVL93",
    use: "Exact owned model, dimensions, two-tone grid, and 30°/45°/60° angle guides.",
  },
] as const;

export const QUICK_HST_CHART = [1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 6, 8, 9].map(
  (finished) => [
    finished,
    finished + 0.5,
    hstPlan(finished, 1, "two").trimFriendlyStart,
    hstPlan(finished, 1, "four").trimFriendlyStart,
    hstPlan(finished, 1, "eight").trimFriendlyStart,
  ] as const,
);
