import { hstPlan } from "./math";

export type GuideNavItem = {
  href: string;
  label: string;
  shortLabel: string;
  description: string;
};

export const GUIDE_NAV: readonly GuideNavItem[] = [
  {
    href: "/app/quilt-guide",
    label: "Workbench",
    shortLabel: "Home",
    description: "Fast answers and guide map",
  },
  {
    href: "/app/quilt-guide/precut-library",
    label: "Precut sizes",
    shortLabel: "Precuts",
    description: "Layer squares, charms, strips, and mixing",
  },
  {
    href: "/app/quilt-guide/triangle-school",
    label: "Triangle units",
    shortLabel: "Triangles",
    description: "HST, QST, and Flying Geese math",
  },
  {
    href: "/app/quilt-guide/block-library",
    label: "Quilt blocks",
    shortLabel: "Blocks",
    description: "Named traditional and modern recipes",
  },
  {
    href: "/app/quilt-guide/construction-methods",
    label: "Construction methods",
    shortLabel: "Methods",
    description: "Traditional and modern ways to assemble patchwork",
  },
  {
    href: "/app/quilt-guide/quilt-planner",
    label: "Quilt planner",
    shortLabel: "Planner",
    description: "Start with a target and skip the math",
  },
  {
    href: "/app/quilt-guide/ruler-cutting",
    label: "Ruler cutting",
    shortLabel: "Cutting",
    description: "Efficient standard and slotted-ruler workflows",
  },
  {
    href: "/app/quilt-guide/finishing",
    label: "Finishing",
    shortLabel: "Finishing",
    description: "Borders, backing, and binding",
  },
  {
    href: "/app/quilt-guide/sources",
    label: "Sources and terms",
    shortLabel: "Sources",
    description: "Research notes, glossary, and caveats",
  },
];

export type Precut = {
  id: "layer" | "charm" | "mini" | "jelly" | "honey" | "fat-quarter" | "fat-eighth";
  genericName: string;
  familiarName: string;
  cut: string;
  directFinish: string;
  modaCount: string;
  description: string;
  color: "tomato" | "gold" | "teal" | "navy" | "lilac" | "pink" | "cream";
};

export const PRECUTS: readonly Precut[] = [
  {
    id: "layer",
    genericName: "10-inch square",
    familiarName: "Layer Cake®",
    cut: "10″ × 10″",
    directFinish: "9½″ square",
    modaCount: "42 pieces",
    description: "Large squares for fast grids, HST batches, QSTs, strips, and subcuts.",
    color: "tomato",
  },
  {
    id: "charm",
    genericName: "5-inch square",
    familiarName: "Charm Pack",
    cut: "5″ × 5″",
    directFinish: "4½″ square",
    modaCount: "42 pieces",
    description: "A versatile patch size for four-patches, HSTs, geese, and scrappy blocks.",
    color: "gold",
  },
  {
    id: "mini",
    genericName: "2½-inch square",
    familiarName: "Mini Charm",
    cut: "2½″ × 2½″",
    directFinish: "2″ square",
    modaCount: "42 pieces",
    description: "Small ready-cut squares that match the cut width of a standard roll strip.",
    color: "teal",
  },
  {
    id: "jelly",
    genericName: "2½-inch WOF strip",
    familiarName: "Jelly Roll®",
    cut: "2½″ × WOF",
    directFinish: "2″ finished width",
    modaCount: "40 strips",
    description: "Strip sets, rails, logs, bindings, sashing, and fast crosscut squares.",
    color: "navy",
  },
  {
    id: "honey",
    genericName: "1½-inch WOF strip",
    familiarName: "Honey Bun",
    cut: "1½″ × WOF",
    directFinish: "1″ finished width",
    modaCount: "40 strips",
    description: "Narrow logs, tiny rails, accent bands, and one-inch finished sashing.",
    color: "lilac",
  },
  {
    id: "fat-quarter",
    genericName: "Fat quarter",
    familiarName: "Fat Quarter",
    cut: "about 18″ × 21″",
    directFinish: "Cut as needed",
    modaCount: "Varies by collection",
    description: "A wide quarter-yard cut that handles larger patches better than a long quarter.",
    color: "pink",
  },
  {
    id: "fat-eighth",
    genericName: "Fat eighth",
    familiarName: "Fat Eighth",
    cut: "about 9″ × 21″",
    directFinish: "Cut as needed",
    modaCount: "Varies by collection",
    description: "A compact sampler cut for blocks, small runs, and controlled scrappiness.",
    color: "cream",
  },
];

export type BlockCutGroup = {
  fabric: string;
  color: "feature" | "background" | "accent" | "secondary" | "scrap";
  cuts: readonly string[];
};

export type QuiltBlock = {
  slug: string;
  name: string;
  family: "traditional" | "modern";
  finishedSize: string;
  unfinishedSize: string;
  difficulty: "Beginner" | "Confident beginner" | "Intermediate";
  unitType: string;
  summary: string;
  diagram: string;
  cuts: readonly BlockCutGroup[];
  steps: readonly {
    phase?: "Prepare" | "Make units" | "Arrange" | "Assemble" | "Check";
    title: string;
    instruction: string;
    details?: readonly string[];
    pressing?: string;
    checkpoint: string;
    diagram?: BlockStepDiagramKind;
  }[];
  precutNote: string;
  accuracyNote: string;
  sourceScope?: "exact recipe" | "construction method";
  sourceNote?: string;
  sources?: readonly {
    label: string;
    url: string;
  }[];
};

export type BlockStepDiagramKind =
  | "cut-pieces"
  | "hst-mark"
  | "hst-cut"
  | "hst-trim"
  | "hst-eight"
  | "flying-geese-mark"
  | "flying-geese-unit"
  | "strip-set"
  | "subcut"
  | "log-rounds"
  | "square-in-square"
  | "stem-unit"
  | "snowball-corner"
  | "heart-halves"
  | "corner-units"
  | "quadrants"
  | "layout"
  | "rows"
  | "final";

const bg = (cuts: readonly string[]): BlockCutGroup => ({
  fabric: "Background",
  color: "background",
  cuts,
});
const feature = (cuts: readonly string[]): BlockCutGroup => ({
  fabric: "Feature",
  color: "feature",
  cuts,
});
const accent = (cuts: readonly string[]): BlockCutGroup => ({
  fabric: "Accent",
  color: "accent",
  cuts,
});
const secondary = (cuts: readonly string[]): BlockCutGroup => ({
  fabric: "Secondary",
  color: "secondary",
  cuts,
});
const scraps = (cuts: readonly string[]): BlockCutGroup => ({
  fabric: "Assorted scraps",
  color: "scrap",
  cuts,
});

const ALL_QUILT_BLOCKS: readonly QuiltBlock[] = [
  {
    slug: "four-patch",
    name: "Four Patch",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "Plain squares",
    summary: "The essential two-by-two checkerboard and a clean first lesson in seam nesting.",
    diagram: "four-patch",
    cuts: [feature(["2 — 6½″ squares"]), bg(["2 — 6½″ squares"])],
    steps: [
      { title: "Pair", instruction: "Place one feature and one background square right sides together. Sew one side at a scant ¼″. Repeat with the second pair.", checkpoint: "Each pair is 6½″ × 12½″ raw." },
      { title: "Press opposite", instruction: "Press one pair toward the feature and the other toward the background so the center seams will nest.", checkpoint: "Both pairs stay flat and square." },
      { title: "Nest", instruction: "Rotate one pair. Nest the center seams and pin at the match point.", checkpoint: "Alternating colors form a checkerboard." },
      { title: "Join", instruction: "Sew the long center seam, press, and square only if needed.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Cut 6½″ squares from yardage or a 10″ square. A full charm is too small for this 12″ version.",
    accuracyNote: "The center intersection is the visual target; nesting opposing seam allowances makes it reliable.",
    sources: [{ label: "AllPeopleQuilt — 12″ Four Patch cutting and assembly", url: "https://www.allpeoplequilt.com/quilt-patterns/quilt-throws/good-sports" }],
  },
  {
    slug: "nine-patch",
    name: "Nine Patch",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "3 × 3 grid",
    summary: "Nine equal patches arranged in three rows—the foundation of dozens of named blocks.",
    diagram: "nine-patch",
    cuts: [feature(["5 — 4½″ squares"]), bg(["4 — 4½″ squares"])],
    steps: [
      { title: "Lay out", instruction: "Arrange three rows of three, alternating feature and background squares with feature at center.", checkpoint: "Each row contains three 4½″ squares." },
      { title: "Chain-piece", instruction: "Sew the first two columns in each row, then add the third column without clipping threads between rows.", checkpoint: "Three row units measure 4½″ × 12½″." },
      { title: "Press", instruction: "Press row 1 and 3 seams toward the feature; press row 2 the opposite way.", checkpoint: "Adjacent row seams nest." },
      { title: "Join rows", instruction: "Match, pin, and sew the two horizontal seams. Press the final block flat.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Trim nine 5″ charms to 4½″ for a precut-perfect version.",
    accuracyNote: "Measure each row before joining; it should be exactly 12½″ long.",
    sources: [{ label: "Polka Dot Chair — 12″ Nine Patch photo tutorial", url: "https://www.polkadotchair.com/nine-patch-quilt-block-tutorial-for-the-block-challenge/" }],
  },
  {
    slug: "sixteen-patch",
    name: "Sixteen Patch",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "4 × 4 grid",
    summary: "A rhythmic checkerboard with smaller scale and excellent strip-piecing potential.",
    diagram: "sixteen-patch",
    cuts: [feature(["8 — 3½″ squares"]), bg(["8 — 3½″ squares"])],
    steps: [
      { title: "Make pairs", instruction: "Sew feature and background squares into eight alternating pairs.", checkpoint: "Each pair is 3½″ × 6½″ raw." },
      { title: "Build rows", instruction: "Join two pairs per row, reversing every other pair to maintain the checkerboard.", checkpoint: "Four rows measure 3½″ × 12½″." },
      { title: "Press for nesting", instruction: "Press odd rows one direction and even rows the opposite direction.", checkpoint: "All vertical seams nest between rows." },
      { title: "Join four rows", instruction: "Sew rows in order, pinning at every match point. Press the block.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "A 10″ square yields four 3½″ squares with useful leftovers; strip piecing is faster for multiples.",
    accuracyNote: "Tiny errors repeat across four columns, so verify the first row before chain-piecing the rest.",
    sources: [{ label: "Darcy Quilts — 12″ Sixteen Patch strip-piecing tutorial", url: "https://darcyquilts.com/how-to-make-a-16-patch-quilt-block-tutorial/" }],
  },
  {
    slug: "rail-fence",
    name: "Rail Fence",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "Jelly-roll strip set",
    summary: "Three-strip rails rotated by quarter turns for movement with almost no fussy piecing.",
    diagram: "rail-fence",
    cuts: [feature(["1 — 2½″ × 28″ strip"]), accent(["1 — 2½″ × 28″ strip"]), bg(["1 — 2½″ × 28″ strip"])],
    steps: [
      { phase: "Make units", title: "Sew the three-strip set", instruction: "Sew the feature strip to the accent strip along the full 28″ length. Add the background strip to the other side.", details: ["Alternate the direction of the long seams to reduce bowing.", "Keep raw edges aligned without pulling either layer."], checkpoint: "Strip set is 6½″ wide.", diagram: "strip-set" },
      { phase: "Check", title: "Press and measure", instruction: "Set both seams, then press open for the flattest result or consistently toward the darker fabric. Measure the strip set at several points.", checkpoint: "Full strip set remains 6½″ wide and straight.", diagram: "strip-set" },
      { phase: "Prepare", title: "Square one end and subcut", instruction: "Trim one short end perpendicular to the long seams. From that clean edge, cut four 6½″-wide segments.", checkpoint: "Four rail units at 6½″ square.", diagram: "subcut" },
      { phase: "Arrange", title: "Rotate the four rail units", instruction: "Arrange the units in a 2 × 2 grid. Turn each unit 90° from the previous one so the rails create the selected woven or zigzag layout.", checkpoint: "All four units match the final block map.", diagram: "layout" },
      { phase: "Assemble", title: "Join the block", instruction: "Sew two rows. Press the rows in opposite directions, nest the center seams, and join the rows.", checkpoint: "12½″ raw / 12″ finished.", diagram: "final" },
    ],
    precutNote: "Use three Jelly Roll strips; sew full WOF strip sets and crosscut at the measured 6½″ raw width for multiples.",
    accuracyNote: "Alternate the direction you sew long strip sets to reduce bowing.",
    sources: [{ label: "Polka Dot Chair — 12″ Rail Fence photo tutorial", url: "https://www.polkadotchair.com/rail-fence-quilt-block-tutorial-easy-12-block-for-beginners/" }],
  },
  {
    slug: "log-cabin",
    name: "Log Cabin",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Sequential logs",
    summary: "A center square built outward with twelve numbered logs, alternating two light and two dark.",
    diagram: "log-cabin",
    cuts: [
      { fabric: "Center", color: "accent", cuts: ["1 — 3½″ center square"] },
      { fabric: "Light logs", color: "background", cuts: ["1 — 2″ × 3½″ (log 1)", "1 — 2″ × 5″ (log 2)", "1 — 2″ × 6½″ (log 5)", "1 — 2″ × 8″ (log 6)", "1 — 2″ × 9½″ (log 9)", "1 — 2″ × 11″ (log 10)"] },
      { fabric: "Dark logs", color: "feature", cuts: ["1 — 2″ × 5″ (log 3)", "1 — 2″ × 6½″ (log 4)", "1 — 2″ × 8″ (log 7)", "1 — 2″ × 9½″ (log 8)", "1 — 2″ × 11″ (log 11)", "1 — 2″ × 12½″ (log 12)"] },
    ],
    steps: [
      { phase: "Prepare", title: "Number all twelve logs", instruction: "Keep the six light and six dark 2″-wide logs in separate stacks. Label each log 1 through 12 using the number printed in the cutting list.", details: ["The block grows counterclockwise: top, left, bottom, right, then repeat.", "Use the full cut length listed; never stretch a short log to make it fit."], checkpoint: "One center square and exactly twelve numbered logs are accounted for.", diagram: "cut-pieces" },
      { phase: "Make units", title: "Add light logs 1 and 2", instruction: "Sew light log 1, 2″ × 3½″, to the top edge of the center. Press away from the center. Sew light log 2, 2″ × 5″, to the left edge so it spans both the center and log 1.", pressing: "Set each seam first, then press the log away from the center without dragging the iron.", checkpoint: "After log 2, the unit measures 5″ square and both light logs meet at the upper-left corner.", diagram: "log-rounds" },
      { phase: "Make units", title: "Add dark logs 3 and 4", instruction: "Sew dark log 3, 2″ × 5″, across the bottom. Sew dark log 4, 2″ × 6½″, along the right edge. Press outward after each seam.", checkpoint: "After log 4, the unit measures 6½″ square: light is top/left and dark is bottom/right.", diagram: "log-rounds" },
      { phase: "Make units", title: "Add logs 5 through 10", instruction: "Repeat the same counterclockwise path: light log 5 on top, light 6 on left, dark 7 on bottom, dark 8 on right, light 9 on top, then light 10 on left.", details: ["The lengths are 6½″, 8″, 8″, 9½″, 9½″, and 11″ in that order.", "Measure after each pair. Correct a bowed edge before adding another log."], checkpoint: "After log 10, the unit measures 11″ square with the numbered diagram still matching your work.", diagram: "log-rounds" },
      { phase: "Assemble", title: "Finish with dark logs 11 and 12", instruction: "Sew dark log 11, 2″ × 11″, across the bottom. Finish with dark log 12, 2″ × 12½″, along the right edge. Press both seams away from the center.", checkpoint: "The complete block measures 12½″ square: the final dark logs form the bottom and right outside edges.", diagram: "log-rounds" },
      { phase: "Check", title: "Square the block", instruction: "Align a 12½″ square ruler with the block center and trim only the outside edge. Confirm the center is not pulled off square.", checkpoint: "12½″ raw / 12″ finished.", diagram: "final" },
    ],
    precutNote: "This verified 12″ version uses 2″-wide logs, so trim Jelly Roll strips from 2½″ to 2″ before cutting the listed lengths.",
    accuracyNote: "Check after every two logs; a small early error grows through every later round.",
    sources: [{ label: "Polka Dot Chair — 12″ Log Cabin photo tutorial", url: "https://www.polkadotchair.com/how-to-make-a-log-cabin-quilt-block-for-the-quilt-block-challenge/" }],
  },
  {
    slug: "courthouse-steps",
    name: "Courthouse Steps",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Paired opposite logs",
    summary: "A Log Cabin relative built in symmetrical pairs on opposite sides of the center.",
    diagram: "courthouse-steps",
    cuts: [accent(["1 — 4½″ center square"]), feature(["2 — 2½″ × 4½″", "2 — 2½″ × 8½″"]), bg(["2 — 2½″ × 8½″", "2 — 2½″ × 12½″"])],
    steps: [
      { title: "Side pair", instruction: "Add 2½″ × 4½″ feature logs to the left and right of the center. Press outward.", checkpoint: "Unit is 4½″ × 8½″." },
      { title: "Top/bottom pair", instruction: "Add 2½″ × 8½″ background logs to top and bottom.", checkpoint: "Unit is 8½″ square." },
      { title: "Repeat outward", instruction: "Add the 2½″ × 8½″ feature side pair, then the 2½″ × 12½″ background top/bottom pair.", checkpoint: "Opposite logs mirror one another." },
      { title: "Final check", instruction: "Press from the center outward and square the outside edge if needed.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Every log is 2½″ wide, so Jelly Roll strips work without width trimming.",
    accuracyNote: "Center each opposite log pair so the block grows symmetrically.",
    sourceScope: "construction method",
    sourceNote: "Courthouse Steps can be drafted with many center and log widths. The linked 12″ tutorial verifies the paired-opposite-log sequence; this page’s listed dimensions were independently checked to total 12½″ raw.",
    sources: [{ label: "Quilts By Jen — 12″ Courthouse Steps construction", url: "https://quiltsbyjen.ca/courthouse-steps-quilt-block/" }],
  },
  {
    slug: "pinwheel",
    name: "Pinwheel",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Four HSTs",
    summary: "Four large half-square triangles spin around one crisp center point.",
    diagram: "pinwheel",
    cuts: [feature(["2 — 7″ squares for HSTs"]), bg(["2 — 7″ squares for HSTs"])],
    steps: [
      { title: "Mark", instruction: "Draw one diagonal on the wrong side of both background squares. Pair each with a feature square, right sides together.", checkpoint: "Two layered square pairs." },
      { title: "Sew and split", instruction: "Sew ¼″ on both sides of each line, cut on the lines, then press toward the feature.", checkpoint: "Four oversized HSTs." },
      { title: "Trim and spin", instruction: "Trim every HST to 6½″, aligning the ruler’s 45° line with the seam. Arrange the feature triangles in a pinwheel.", checkpoint: "Four 6½″ units." },
      { title: "Join", instruction: "Sew two rows, then join through the center with seams nested or fanned.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "This size needs yardage. For a larger 18″-finished pinwheel, use two contrasting pairs of 10″ squares—four squares total—and trim the four HSTs to 9½″.",
    accuracyNote: "Preserve the ¼″ seam allowance beyond the center tips when trimming.",
    sources: [{ label: "Adventures of a DIY Mom — 12″ Pinwheel cutting chart and photo tutorial", url: "https://www.adventuresofadiymom.com/2024/11/how-to-make-pinwheel-quilt-block.html" }],
  },
  {
    slug: "friendship-star",
    name: "Friendship Star",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "HST star",
    summary: "A five-patch star whose four HST points orbit a contrasting center.",
    diagram: "friendship-star",
    cuts: [feature(["1 — 4½″ center", "2 — 5″ HST squares"]), bg(["4 — 4½″ corners", "2 — 5″ HST squares"])],
    steps: [
      { title: "Make HSTs", instruction: "Use the four 5″ squares to make four HSTs two at a time. Press and trim each to 4½″.", checkpoint: "Four 4″-finished HSTs." },
      { title: "Lay out the star", instruction: "Place the feature square at center, plain backgrounds at corners, and HSTs at the four side positions.", checkpoint: "All feature triangles spin the same direction." },
      { title: "Sew rows", instruction: "Join each row of three. Press the middle row away from center and outer rows toward center.", checkpoint: "Three 4½″ × 12½″ rows." },
      { title: "Assemble", instruction: "Nest row seams, sew, and press the complete star.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Trim 5″ charms only after making the HSTs; four extra charms can become the plain corners.",
    accuracyNote: "Either clockwise or counterclockwise spin is valid—keep all four points consistent.",
    sources: [{ label: "Polka Dot Chair — 12″ Friendship Star photo tutorial", url: "https://www.polkadotchair.com/friendship-star-quilt-block-tutorial/" }],
  },
  {
    slug: "shoo-fly",
    name: "Shoo Fly",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "HST corners",
    summary: "A sturdy nine-patch variation with feature triangles pointing into a square center.",
    diagram: "shoo-fly",
    cuts: [feature(["1 — 4½″ center", "2 — 5″ HST squares"]), bg(["4 — 4½″ side squares", "2 — 5″ HST squares"])],
    steps: [
      { title: "Make HSTs", instruction: "Pair the 5″ squares and make four two-at-a-time HSTs. Trim to 4½″.", checkpoint: "Four identical corner units." },
      { title: "Aim inward", instruction: "Set HSTs in the four corners with every feature triangle touching the feature center diagonally. Fill side positions with background.", checkpoint: "Feature makes a broad X shape." },
      { title: "Join rows", instruction: "Sew three rows, pressing adjacent rows in opposite directions.", checkpoint: "Row seams will nest." },
      { title: "Finish", instruction: "Join rows and press. Check that no corner point is closer than ¼″ to the raw edge.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Charm squares work for every patch; trim plain charms to 4½″ and HSTs after piecing.",
    accuracyNote: "Orientation distinguishes Shoo Fly from other star-like nine patches; point feature triangles inward.",
    sources: [{ label: "Polka Dot Chair — 12″ Shoo Fly photo tutorial", url: "https://www.polkadotchair.com/shoo-fly-quilt-block-tutorial/" }],
  },
  {
    slug: "hourglass-quartet",
    name: "Hourglass Quartet",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Intermediate",
    unitType: "Four QSTs",
    summary: "Four oversized hourglass units meet in a graphic burst of quarter-square triangles.",
    diagram: "hourglass-quartet",
    cuts: [feature(["2 — 7½″ QST squares"]), bg(["2 — 7½″ QST squares"])],
    steps: [
      { title: "First diagonal", instruction: "Pair one feature and one background square. Make two HSTs, pressing both seams the same direction. Repeat.", checkpoint: "Four oversized HSTs." },
      { title: "Opposite diagonal", instruction: "Pair HSTs right sides together with opposite colors touching and seams nested. Mark across the unsewn diagonal, sew both sides, and cut.", checkpoint: "Four hourglass units." },
      { title: "Trim", instruction: "Align the ruler center and both 45° diagonals; trim each QST to 6½″.", checkpoint: "Center intersection stays at 3¼″." },
      { title: "Join quartet", instruction: "Arrange the hourglasses in a two-by-two rotation and assemble like a Four Patch.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "This size requires 7½″ squares; 10″ layer squares leave generous room and can be trimmed first.",
    accuracyNote: "Trim equally from all four sides so the center remains centered.",
    sourceScope: "construction method",
    sourceNote: "The linked 12″ pattern verifies the four-hourglass arrangement. This guide uses an oversized two-pass QST method so every 6½″ raw unit can be trimmed accurately before assembly.",
    sources: [{ label: "AccuQuilt — 12″ Hourglass block arrangement", url: "https://www.accuquilt.com/media/emails/QQK17-PatternBook.pdf" }],
  },
  {
    slug: "ohio-star",
    name: "Ohio Star",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Intermediate",
    unitType: "QST star points",
    summary: "A canonical nine-patch star with four hourglass point units and calm square corners.",
    diagram: "ohio-star",
    cuts: [feature(["1 — 4½″ center", "2 — 5½″ QST squares"]), bg(["4 — 4½″ corners", "2 — 5½″ QST squares"])],
    steps: [
      { title: "Make QSTs", instruction: "Use the 5½″ squares to make four trim-friendly hourglass units through two diagonal sewing passes.", checkpoint: "Four QSTs ready to trim." },
      { title: "Trim points", instruction: "Square every QST to 4½″ with the center at 2¼″ and diagonal seams running corner to corner.", checkpoint: "Points keep a ¼″ allowance." },
      { title: "Lay out", instruction: "Place the feature square in the center, background squares at corners, and QSTs at the side positions with feature points facing outward.", checkpoint: "A clear eight-point star appears." },
      { title: "Sew 3 × 3", instruction: "Join rows, press for nesting, then join the three rows.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Layer squares are an easy source, but each 10″ square yields only one 5½″ start. You need four 10″ squares total—two feature and two background.",
    accuracyNote: "The QST center is the trimming anchor; do not trim by outer edges alone.",
    sources: [
      { label: "Polka Dot Chair — 12″ Ohio Star photo tutorial", url: "https://www.polkadotchair.com/how-to-make-a-12-inch-ohio-star-quilt-block/" },
      { label: "Generations Quilt Patterns — Ohio Star cutting charts and QST orientation", url: "https://www.generations-quilt-patterns.com/ohio-star-quilt-block.html" },
    ],
  },
  {
    slug: "churn-dash",
    name: "Churn Dash",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "HST corners + bar units",
    summary: "A beloved frame-like block combining corner triangles, side bars, and a quiet center.",
    diagram: "churn-dash",
    cuts: [feature(["2 — 5″ HST squares", "4 — 2½″ × 4½″ bars"]), bg(["2 — 5″ HST squares", "4 — 2½″ × 4½″ bars", "1 — 4½″ center"])],
    steps: [
      { phase: "Prepare", title: "Mark the HST squares", instruction: "Draw one diagonal line on the wrong side of each 5″ background square. Pair each marked square with a 5″ feature square, right sides together.", checkpoint: "Two matched 5″ square pairs.", diagram: "hst-mark" },
      { phase: "Make units", title: "Sew and cut four HSTs", instruction: "Sew a scant ¼″ on both sides of each marked line. Cut directly on the marked lines, open the four units, and press toward the darker fabric.", checkpoint: "Four oversized HST units.", diagram: "hst-cut" },
      { phase: "Check", title: "Trim the corner units", instruction: "Place the ruler’s 45° line on the diagonal seam. Trim each HST to exactly 4½″, keeping the seam in both opposite corners.", checkpoint: "Four HSTs at 4½″ square.", diagram: "hst-trim" },
      { phase: "Make units", title: "Make the four side-bar units", instruction: "Sew one 2½″ × 4½″ feature bar to one background bar along the 4½″ edge. Repeat four times.", pressing: "Press every bar-unit seam toward the feature fabric.", checkpoint: "Four bar units at 4½″ square.", diagram: "corner-units" },
      { phase: "Arrange", title: "Lay out the nine units", instruction: "Put the plain background square in the center. Place bar units at the four sides with feature bars touching the center. Put HSTs at the corners with feature triangles pointing toward the center.", details: ["Check all four bars before sewing.", "The feature fabric should form one continuous churn-dash frame."], checkpoint: "The layout matches the finished block map.", diagram: "layout" },
      { phase: "Assemble", title: "Sew three rows", instruction: "Join the three units in each row. Press the top and bottom rows away from the center unit; press the middle row toward the center so the seams nest.", checkpoint: "Three rows, each 4½″ × 12½″.", diagram: "rows" },
      { phase: "Assemble", title: "Join the rows", instruction: "Nest and pin the row seams. Sew the two long seams, press the block flat, and square only if needed.", checkpoint: "12½″ raw / 12″ finished.", diagram: "final" },
    ],
    precutNote: "Use charms for HST starts; Jelly Roll strips supply the 2½″ bars efficiently.",
    accuracyNote: "Check bar-unit orientation before sewing rows—the feature bars all face the center.",
    sources: [{ label: "Polka Dot Chair — 12″ Churn Dash photo tutorial", url: "https://www.polkadotchair.com/quilt-block-challenge-churn-dash-blocks/" }],
  },
  {
    slug: "sawtooth-star",
    name: "Sawtooth Star",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Four Flying Geese, star fabric in the corners",
    summary: "The traditional eight-point star: two star-fabric triangles on each side of a large center square.",
    diagram: "sawtooth-star",
    cuts: [
      { fabric: "Center", color: "accent", cuts: ["1 — 6½″ center square"] },
      { fabric: "Star points", color: "feature", cuts: ["8 — 3½″ star-point squares"] },
      bg(["4 — 3½″ × 6½″ goose rectangles", "4 — 3½″ corner squares"]),
    ],
    steps: [
      { phase: "Prepare", title: "Mark the star-point squares", instruction: "Draw one diagonal line on the wrong side of all eight 3½″ feature squares. Keep the background rectangles, background corners, and center square unmarked.", checkpoint: "Eight star-point squares are marked corner to corner.", diagram: "flying-geese-mark" },
      { phase: "Make units", title: "Sew the first point triangle", instruction: "Place one marked feature square on the left end of each 3½″ × 6½″ background rectangle, right sides together, with the line oriented as shown. Sew directly on the line.", details: ["Flip the corner open before trimming to confirm it covers the rectangle.", "Trim the outside layers ¼″ beyond the seam, then press open."], checkpoint: "Four one-sided units remain 3½″ × 6½″.", diagram: "flying-geese-mark" },
      { phase: "Make units", title: "Complete the four Flying Geese", instruction: "Place a second marked star-point square on the other end of each rectangle as a mirror image. Sew, check coverage, trim ¼″ beyond the seam, and press open.", details: ["The two small corner triangles are the star fabric.", "The large center triangle remains background fabric."], checkpoint: "Four Flying Geese at 3½″ × 6½″; each large background triangle meets the midpoint of a long edge.", diagram: "flying-geese-unit" },
      { phase: "Arrange", title: "Point the background triangles toward the center", instruction: "Place the 6½″ center square in the middle. Put one Flying Geese unit above, below, left, and right. Rotate each unit so its large background triangle points toward the center square; the two star-fabric triangles point outward. Place 3½″ background squares at the four corners.", details: ["This color placement—not the opposite one—creates eight sawtooth points.", "Count two star points on every side before sewing."], checkpoint: "Eight separate star-fabric points surround the center: two top, two right, two bottom, and two left.", diagram: "layout" },
      { phase: "Assemble", title: "Sew the three rows", instruction: "Top row: corner, goose with its large background triangle pointing down, corner. Middle row: goose pointing right, center square, goose pointing left. Bottom row: corner, goose pointing up, corner. In every row, the large background triangles face the center square.", pressing: "Press the top and bottom rows away from their geese; press the middle row toward the center square so intersections nest.", checkpoint: "Three rows, each 12½″ wide, with all eight star-fabric points facing outward.", diagram: "rows" },
      { phase: "Assemble", title: "Join the star", instruction: "Nest and pin the row seams. Sew the two long seams while watching the goose tip intersections. Press and square only the outside edge if necessary.", checkpoint: "12½″ raw / 12″ finished.", diagram: "final" },
    ],
    precutNote: "One 10″ square supplies the center and two more can yield the four background rectangles. Charms can supply the 3½″ star-point and corner squares. Use the same fabric for the center and star points if you want one continuous-color star. A 2½″ strip is too narrow for this recipe.",
    accuracyNote: "Before joining, verify the large background triangle in every Flying Geese unit points toward the center. Preserve ¼″ of fabric beyond every visible star-point tip when sewing the surrounding seams.",
    sources: [
      { label: "Polka Dot Chair — 12″ Sawtooth Star photo tutorial", url: "https://www.polkadotchair.com/sawtooth-star-quilt-block-pattern/" },
      { label: "3rd Story Workshop — Sawtooth Star pattern and Flying Geese checks", url: "https://3rdstoryworkshop.com/free-sawtooth-star-pattern" },
      { label: "Threadbare Creations — Sawtooth Star grid and traditional names", url: "https://threadbarecreations.blogspot.com/2019/08/classic-quilt-blocks-sawtooth-star.html" },
    ],
  },
  {
    slug: "dutchmans-puzzle",
    name: "Dutchman’s Puzzle",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Intermediate",
    unitType: "Eight Flying Geese",
    summary: "Pairs of geese sweep around the center in a bold rotating puzzle.",
    diagram: "dutchmans-puzzle",
    cuts: [feature(["4 — 3½″ × 6½″ goose bodies"]), accent(["4 — 3½″ × 6½″ goose bodies"]), bg(["16 — 3½″ sky squares"])],
    steps: [
      { title: "Make eight geese", instruction: "Use stitch-and-flip sky squares on both ends of every body rectangle. Make four geese in each feature color.", checkpoint: "Eight geese at 3½″ × 6½″." },
      { title: "Pair colors", instruction: "Stack one feature goose and one accent goose along their long edges, both pointing the same direction. Make four quadrants.", checkpoint: "Four 6½″ squares." },
      { title: "Rotate quadrants", instruction: "Arrange the four paired quadrants so their points circle clockwise around the block center.", checkpoint: "No pair points outward from the center." },
      { title: "Assemble", instruction: "Join quadrants in two rows, then sew the center seam.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Layer squares can be subcut for bodies and charms for sky squares; verify directional prints before flipping corners.",
    accuracyNote: "Make one test goose and confirm 3½″ × 6½″ before chain-piecing the remaining seven.",
    sourceScope: "construction method",
    sourceNote: "The linked tutorial verifies the 12″ map, eight 3½″ × 6½″ Flying Geese, and paired-quadrant rotation. It demonstrates no-waste geese; this page uses the equally valid one-at-a-time stitch-and-flip method so the cut list stays beginner-readable.",
    sources: [{ label: "SewCanShe — 12″ Dutchman’s Puzzle photo tutorial", url: "https://sewcanshe.com/2014-5-2-classic-blocks-fresh-fabrics-for-may-the-dutchmans-puzzle/" }],
  },
  {
    slug: "jacobs-ladder",
    name: "Jacob’s Ladder",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Five Four Patches + four HSTs",
    summary: "A diagonal chain emerges from alternating Four Patches and half-square triangles.",
    diagram: "jacobs-ladder",
    cuts: [feature(["10 — 2½″ squares", "2 — 5″ HST squares"]), bg(["10 — 2½″ squares", "2 — 5″ HST squares"])],
    steps: [
      { title: "Five Four Patches", instruction: "Pair 2½″ feature and background squares, press in opposite directions, then join pairs into five checkerboard Four Patches.", checkpoint: "Five units trim to 4½″." },
      { title: "Four HSTs", instruction: "Use the 5″ squares to make four two-at-a-time HSTs. Trim to 4½″.", checkpoint: "Nine total 4½″ subunits." },
      { title: "Build the ladder", instruction: "Place Four Patches at all four corners and center with feature squares at upper-left and lower-right in every unit. Fill the four side positions with HSTs as shown so the feature fabric forms a continuous diagonal ladder from lower left to upper right.", checkpoint: "All five Four Patches share one orientation and the four HSTs continue the diagonal path." },
      { title: "Join rows", instruction: "Sew the 3 × 3 grid, nesting seams where possible.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Mini charms are ready for the Four Patches; charms make the HSTs with trimming room.",
    accuracyNote: "The official map keeps all five Four Patches in the same checkerboard orientation. A quarter-turn of the center unit breaks the ladder.",
    sources: [{ label: "Riley Blake Designs — 12″ Jacob’s Ladder instructions", url: "https://www.rileyblakedesigns.com/assets/images/sewalongs/BuildingBlocks/2022/JacobsLadder.pdf" }],
  },
  {
    slug: "snowball",
    name: "Snowball",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "Stitch-and-flip corners",
    summary: "A broad feature square with clipped corners; this recipe declares a one-third corner proportion.",
    diagram: "snowball",
    cuts: [feature(["1 — 12½″ square"]), bg(["4 — 4½″ corner squares"])],
    steps: [
      { title: "Mark corners", instruction: "Draw one diagonal on the wrong side of all four 4½″ background squares.", checkpoint: "Lines run corner to corner." },
      { title: "Sew", instruction: "Place one marked square at each feature-square corner, right sides together, and sew on every line.", checkpoint: "Marked triangles point toward the large square center." },
      { title: "Trim and press", instruction: "Trim ¼″ outside each seam, removing the outer corner layers. Press sky triangles outward.", checkpoint: "Block remains 12½″ square." },
      { title: "Check the frame", instruction: "Square the raw outer edge and confirm feature points stop ¼″ before each corner seam.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "A Layer Cake makes a smaller 9½″-finished Snowball; scale corners to the declared ratio or follow that pattern’s exact recipe.",
    accuracyNote: "Snowball proportions vary by pattern; this page intentionally uses 4″-finished corner triangles.",
    sourceScope: "construction method",
    sourceNote: "Snowball corner proportions are not universal. The linked 12″ tutorial verifies the stitch-and-flip construction; this Monosyth version deliberately uses larger 4½″ cut corner squares for a 4″-finished corner triangle.",
    sources: [{ label: "Piece N Quilt — 12″ Snowball stitch-and-flip tutorial", url: "https://www.pieceandquilt.com/2015/12/how-to-snowball-quilt-block-basics.html" }],
  },
  {
    slug: "bear-paw",
    name: "Bear Paw",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Intermediate",
    unitType: "Four paw quadrants + sashing",
    summary: "Four clawed paws gather around a narrow center sashing cross.",
    diagram: "bear-paw",
    cuts: [feature(["4 — 4″ paw-pad squares", "8 — 3″ HST squares"]), bg(["8 — 3″ HST squares", "4 — 2¼″ quadrant corners", "4 — 2″ × 5¾″ sashing bars", "1 — 2″ center square"])],
    steps: [
      { phase: "Make units", title: "Make sixteen claw HSTs", instruction: "Pair each 3″ feature square with one 3″ background square. Sew two HSTs at a time, press toward feature, and trim all sixteen units to 2¼″.", checkpoint: "Sixteen HSTs at 2¼″ square.", diagram: "hst-cut" },
      { phase: "Make units", title: "Build one paw quadrant", instruction: "Join two HSTs above a 4″ feature pad and two HSTs beside it. Add one 2¼″ background square in the empty outside corner. Point every feature triangle toward the pad.", checkpoint: "One paw quadrant at 5¾″ square.", diagram: "corner-units" },
      { phase: "Make units", title: "Make the other three paws", instruction: "Repeat the same construction three times. Rotate completed paw quadrants only after all four are sewn and square.", checkpoint: "Four matching 5¾″ paw quadrants.", diagram: "quadrants" },
      { phase: "Arrange", title: "Place the sashing cross", instruction: "Arrange the four paws around the center. Put a 2″ × 5¾″ background bar between each pair and the 2″ square at the exact center.", checkpoint: "All claws point away from their own pad and the sashing forms a cross.", diagram: "layout" },
      { phase: "Assemble", title: "Join three sections", instruction: "Sew the top paw row, the center bar-square-bar row, and the bottom paw row. Press adjacent rows in opposite directions and join.", checkpoint: "12½″ raw / 12″ finished.", diagram: "rows" },
    ],
    precutNote: "Charms easily supply the 3″ HST starts and 4″ paw pads. Cut the 2″ sashing pieces from yardage or narrower strip subcuts.",
    accuracyNote: "Make and measure one 5¾″ paw quadrant before batch sewing; all sixteen claws must point toward their pad.",
    sources: [{ label: "Polka Dot Chair — 12″ Bear Paw photo tutorial", url: "https://www.polkadotchair.com/bear-paw-quilt-block-tutorials/" }],
  },
  {
    slug: "disappearing-nine-patch",
    name: "Disappearing Nine Patch",
    family: "traditional",
    finishedSize: "13″",
    unfinishedSize: "13½″",
    difficulty: "Confident beginner",
    unitType: "Cut-and-rearrange Nine Patch",
    summary: "A sewn Nine Patch is quartered, rotated, and resewn into a surprisingly complex grid.",
    diagram: "disappearing-nine-patch",
    cuts: [scraps(["9 — 5″ charm squares"])],
    steps: [
      { title: "Make a Nine Patch", instruction: "Arrange and sew nine 5″ charms as three rows of three. Press for nesting.", checkpoint: "The first block measures 14″ raw." },
      { title: "Quarter it", instruction: "Measure 7″ from either raw edge and cut vertically through center. Without shifting, cut horizontally at 7″.", checkpoint: "Four 7″ square quarters." },
      { title: "Rearrange", instruction: "Rotate two opposite quarters 180°, or swap quarters, keeping all four raw squares in a two-by-two layout.", checkpoint: "Small center patches move to new positions." },
      { title: "Resew", instruction: "Join the four quarters like a Four Patch and press.", checkpoint: "13½″ raw / 13″ finished." },
    ],
    precutNote: "This version is designed specifically for nine untrimmed 5″ charm squares.",
    accuracyNote: "The general finished-size formula for this version is three times the starting square minus 2″.",
    sources: [
      { label: "Kate Colleran Designs — 5″-square Disappearing Nine Patch size proof", url: "https://katecollerandesigns.com/exploring-quilting-basics-the-disappearing-9-patch-block/" },
      { label: "Leah Day — Disappearing Nine Patch precut planning chart", url: "https://leahday.com/blogs/free/disappearing-9-patch" },
    ],
  },
  {
    slug: "modern-plus",
    name: "Modern Plus",
    family: "modern",
    finishedSize: "10″",
    unfinishedSize: "10½″",
    difficulty: "Beginner",
    unitType: "5 × 5 mini grid",
    summary: "A crisp plus sign drawn through a field of small squares with bold negative space.",
    diagram: "modern-plus",
    cuts: [feature(["9 — 2½″ squares"]), bg(["16 — 2½″ squares"])],
    steps: [
      { title: "Map the plus", instruction: "Lay out a 5 × 5 grid with feature squares filling the complete center row and center column.", checkpoint: "Nine feature squares form one continuous plus." },
      { title: "Sew rows", instruction: "Chain-piece five rows, keeping each row attached by thread in order.", checkpoint: "Five rows at 2½″ × 10½″." },
      { title: "Press alternating", instruction: "Press odd rows left and even rows right so every vertical seam nests.", checkpoint: "Grid intersections align." },
      { title: "Join", instruction: "Sew the five rows and press the block flat.", checkpoint: "10½″ raw / 10″ finished." },
    ],
    precutNote: "Mini charms are exactly the required cut size—nine feature and sixteen background.",
    accuracyNote: "Keep background values quiet so the plus retains a strong silhouette.",
    sourceScope: "construction method",
    sourceNote: "This 10″ mini-charm layout is Monosyth-drafted. The linked tutorial verifies the same plus-block row construction at quilt scale; the 5 × 5 grid here was independently checked to finish at 10″.",
    sources: [{ label: "Diary of a Quilter — pieced Plus Quilt construction", url: "https://www.diaryofaquilter.com/gratitude-quilt-a-free-plus-quilt-tutorial/" }],
  },
  {
    slug: "hst-chevron",
    name: "HST Chevron",
    family: "modern",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "16 HSTs",
    summary: "Sixteen small HSTs repeat into a clean zigzag with strong directional energy.",
    diagram: "hst-chevron",
    cuts: [feature(["8 — 4″ HST squares"]), bg(["8 — 4″ HST squares"])],
    steps: [
      { title: "Batch HSTs", instruction: "Use the sixteen 4″ squares to make sixteen HSTs two at a time.", checkpoint: "Eight paired batches yield sixteen." },
      { title: "Trim", instruction: "Trim each HST to 3½″ with the 45° seam on the ruler diagonal.", checkpoint: "Sixteen 3″-finished HSTs." },
      { title: "Make chevrons", instruction: "Arrange a 4 × 4 grid. Mirror adjacent HST diagonals in pairs to make two V shapes in each row. Reverse the V direction in the next row so the diagonals connect into continuous zigzag bands.", checkpoint: "Rows alternate V direction and every diagonal continues across a seam." },
      { title: "Assemble grid", instruction: "Join rows, pressing alternating directions, then join all four rows.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Charm squares are ideal HST starts: sew first, then trim the finished units to 3½″.",
    accuracyNote: "Photograph the layout before sewing; one rotated HST breaks the entire chevron rhythm.",
    sourceScope: "construction method",
    sourceNote: "The linked tutorial verifies the same 4 × 4 Chevron layout and 3½″ raw HST units, but makes those units with an eight-at-a-time paper template. This guide uses trim-friendly two-at-a-time HSTs from 4″ squares so a beginner can work without a specialty template.",
    sources: [{ label: "Gathered — 12″ Chevron block layout and HST checkpoints", url: "https://www.gathered.how/sewing-and-quilting/quilting/chevrons-quilt-block-pattern" }],
  },
  {
    slug: "wonky-star",
    name: "Wonky Star",
    family: "modern",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Improvised star-point wedges",
    summary: "An intentionally irregular nine-patch star with lively, individually angled points.",
    diagram: "wonky-star",
    cuts: [feature(["1 — 4½″ center square"]), bg(["8 — 4½″ squares"]), scraps(["8 wedges, each at least 3″ × 5″"])],
    steps: [
      { title: "First point", instruction: "Lay one scrap wedge diagonally across a background square, right sides together. Sew, flip, and confirm it covers a corner; trim the hidden layers.", checkpoint: "Feature wedge reaches one raw edge." },
      { title: "Second point", instruction: "Add a contrasting wedge from the adjacent side. Press and trim the entire point unit back to 4½″. Make four varied units.", checkpoint: "Four side units, each with two wonky points." },
      { title: "Arrange", instruction: "Place the feature square at center, point units at the four sides, and untouched background squares at corners.", checkpoint: "Eight irregular points surround center." },
      { title: "Join nine-patch", instruction: "Sew three rows, then join rows. Preserve ¼″ beyond the innermost point tips.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Use charms trimmed to 4½″ for background and leftovers for the improvised wedges.",
    accuracyNote: "Wonky means varied angles, not missing seam allowance; every finished point still needs room beyond its tip.",
    sources: [{ label: "Scissortail Quilting — 12″ Wonky Star cutting chart and diagrams", url: "https://scissortailquilting.com/wp-content/uploads/dlm_uploads/2019/09/WonkyStarQuiltBlockPattern_Rev1.pdf" }],
  },
  {
    slug: "offset-log-cabin",
    name: "Offset Log Cabin",
    family: "modern",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Unequal-width sequential logs",
    summary: "A true offset Log Cabin: narrow light logs and wider dark logs shift the center and create the illusion of a curve.",
    diagram: "offset-log-cabin",
    cuts: [
      { fabric: "Center / dark", color: "feature", cuts: ["1 — 3½″ center square"] },
      { fabric: "Narrow light logs", color: "background", cuts: ["1 — 1½″ × 3½″ (log 1)", "1 — 1½″ × 4½″ (log 2)", "1 — 1½″ × 6½″ (log 5)", "1 — 1½″ × 7½″ (log 6)", "1 — 1½″ × 9½″ (log 9)", "1 — 1½″ × 10½″ (log 10)"] },
      { fabric: "Wide dark logs", color: "feature", cuts: ["1 — 2½″ × 4½″ (log 3)", "1 — 2½″ × 6½″ (log 4)", "1 — 2½″ × 7½″ (log 7)", "1 — 2½″ × 9½″ (log 8)", "1 — 2½″ × 10½″ (log 11)", "1 — 2½″ × 12½″ (log 12)"] },
    ],
    steps: [
      { phase: "Prepare", title: "Number the unequal-width logs", instruction: "Keep the six 1½″ light logs and six 2½″ dark logs in separate numbered stacks. The center belongs to the dark side.", checkpoint: "One 3½″ center and twelve numbered logs are ready.", diagram: "cut-pieces" },
      { phase: "Make units", title: "Add narrow light logs 1 and 2", instruction: "Sew light log 1 to the top of the center, then light log 2 to the left. Press away from the center after each seam.", checkpoint: "The unit measures 4½″ square after log 2.", diagram: "log-rounds" },
      { phase: "Make units", title: "Add wide dark logs 3 and 4", instruction: "Sew dark log 3 across the bottom, then dark log 4 along the right edge. The wider logs begin shifting the center toward the upper-left.", checkpoint: "The unit measures 6½″ square after log 4.", diagram: "log-rounds" },
      { phase: "Make units", title: "Add logs 5 through 8", instruction: "Repeat the same top, left, bottom, right path: narrow light logs 5 and 6, then wide dark logs 7 and 8. Press and measure after every log pair.", checkpoint: "The unit measures 9½″ square after log 8.", diagram: "log-rounds" },
      { phase: "Assemble", title: "Finish with logs 9 through 12", instruction: "Add narrow light logs 9 and 10, then wide dark logs 11 and 12. Do not substitute equal widths—the unequal widths create the offset.", checkpoint: "12½″ raw / 12″ finished.", diagram: "final" },
    ],
    precutNote: "Jelly Roll strips supply the 2½″ dark logs. Cut the 1½″ light logs from Honey Bun strips or trim wider strips to 1½″.",
    accuracyNote: "Unlike a color-shifted ordinary Log Cabin, a true offset block uses different log widths. Check raw sizes at 4½″, 6½″, 9½″, and 12½″.",
    sourceScope: "construction method",
    sourceNote: "The linked source verifies that a true Offset Log Cabin uses 1½″ light logs and 2½″ dark logs. Its published block finishes at 9″; this page extends the same proven sequence by one full round to finish at 12″.",
    sources: [{ label: "Epida Studio — Offset Log Cabin unequal-width method", url: "https://www.epidastudio.com/log-cabin-sampler-offset-cabin/" }],
  },
  {
    slug: "stacked-coins",
    name: "Stacked Coins",
    family: "modern",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "Pieced coin columns",
    summary: "Two columns of short fabric ‘coins’ float between slim bands of negative space.",
    diagram: "stacked-coins",
    cuts: [scraps(["8 — 4½″ × 3½″ coin rectangles"]), bg(["1 — 2½″ × 12½″ center strip", "2 — 1½″ × 12½″ outer strips"])],
    steps: [
      { title: "Stack coins", instruction: "Divide coin rectangles into two sets of four. Sew each set end to end along 4½″ edges.", checkpoint: "Two columns at 4½″ × 12½″." },
      { title: "Press the stacks", instruction: "Press coin seams in alternating directions or open to keep bulky intersections flat.", checkpoint: "Both columns remain straight." },
      { title: "Insert negative space", instruction: "Sew the 2½″ center strip between coin columns. Add a 1½″ strip to each outside edge.", checkpoint: "Full unit is 12½″ wide." },
      { title: "Square", instruction: "Align a long ruler with the center strip and trim the top/bottom only if necessary.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Charm squares can be trimmed to 4½″ × 3½″ coins; directional prints should all face the same way before stacking.",
    accuracyNote: "Measure each coin column before adding sashing; both must finish at the same 12½″ raw height.",
    sourceScope: "construction method",
    sourceNote: "Stacked Coins varies by quilt and is not one fixed 12″ historical block. The linked tutorial verifies the stacked-strip method; this two-column sampler recipe was independently checked to finish at 12″.",
    sources: [{ label: "Confessions of a Fabric Addict — Stacked Coins construction", url: "https://confessionsofafabricaddict.blogspot.com/2018/02/scrumptious-scraps-quilt-along-stacked.html" }],
  },
  {
    slug: "minimalist-cross",
    name: "Minimalist Cross",
    family: "modern",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "Narrow cross in a 3 × 3 layout",
    summary: "A slim two-inch-finished cross divides four oversized fields of negative space.",
    diagram: "minimalist-cross",
    cuts: [feature(["1 — 2½″ center", "2 — 2½″ × 5½″ vertical arms", "2 — 5½″ × 2½″ horizontal arms"]), bg(["4 — 5½″ squares"])],
    steps: [
      { title: "Build three rows", instruction: "Top and bottom rows are background square, vertical arm, background square. The middle row is horizontal arm, center, horizontal arm.", checkpoint: "Rows are 5½″, 2½″, and 5½″ high." },
      { title: "Join row pieces", instruction: "Sew within each row and press all seams toward the feature cross.", checkpoint: "Every row measures 12½″ wide." },
      { title: "Match center lines", instruction: "Mark or finger-press each row midpoint and align the vertical arm through all three rows.", checkpoint: "Cross is continuous and centered." },
      { title: "Sew rows", instruction: "Join top, middle, and bottom rows; press toward the narrow middle row.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Jelly Roll strips provide every cross piece; layer squares can yield the 5½″ background fields.",
    accuracyNote: "Because the background is quiet, a wandering vertical alignment is visible—match the arm edges, not just raw corners.",
    sourceScope: "construction method",
    sourceNote: "This centered 12″ cross is a Monosyth-drafted grid, not a claim of one canonical named block. Its five-piece cross and four-field geometry were checked directly from the listed cut sizes.",
    sources: [{ label: "Treasurie — Cross block construction and size variations", url: "https://blog.treasurie.com/cross-quilt-blocks/" }],
  },
  {
    slug: "improv-mosaic",
    name: "Improv Mosaic",
    family: "modern",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Intermediate",
    unitType: "Improvisational slabs",
    summary: "Scrap-built slabs are trimmed into controlled quadrants, balancing spontaneity with a reliable final size.",
    diagram: "improv-mosaic",
    cuts: [scraps(["Strips and chunks 1½″–3½″ wide", "Enough to cover four 7″ squares"]), bg(["Optional narrow contrast strips 1″–1½″ wide"])],
    steps: [
      { title: "Build slabs", instruction: "Join scraps into small pairs, then join pairs into four loose slabs at least 7″ square. Vary line lengths and avoid lining up every seam.", checkpoint: "Four slabs cover a 7″ square ruler area." },
      { title: "Press and trim", instruction: "Press each new seam before adding the next piece. Trim four slabs to exactly 6½″ square.", checkpoint: "Four stable, square quadrants." },
      { title: "Rotate for balance", instruction: "Turn quadrants until color, scale, and seam direction feel distributed. Keep bulky intersections away from the center when possible.", checkpoint: "A balanced 2 × 2 mosaic." },
      { title: "Join", instruction: "Assemble like a Four Patch. Press the center seam open to reduce bulk.", checkpoint: "12½″ raw / 12″ finished." },
    ],
    precutNote: "Use orphan mini charms, Jelly Roll ends, and trimming leftovers; this is the intentional scrap-release valve.",
    accuracyNote: "The interior is improvised, but the four 6½″ trimmed quadrants make the final size deterministic.",
    sourceScope: "construction method",
    sourceNote: "Improv piecing has no single canonical patch map. The linked tutorial verifies the sew, press, straighten, and add workflow; this guide controls the final size by trimming four oversized slabs to 6½″ before joining.",
    sources: [{ label: "Diary of a Quilter — 12½″ trimmed improv block workflow", url: "https://www.diaryofaquilter.com/improv-log-cabin-block-tutorial/" }],
  },
  {
    slug: "economy-block",
    name: "Economy Block",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Two square-in-square rounds",
    summary: "A center square framed by two rounds of corner triangles.",
    diagram: "economy-block",
    cuts: [feature(["1 — 6½″ center square"]), accent(["2 — 5½″ squares; cut each once diagonally"]), bg(["2 — 7¼″ squares; cut each once diagonally"])],
    steps: [
      { phase: "Prepare", title: "Cut the border triangles", instruction: "Cut both 5½″ accent squares and both 7¼″ background squares once from corner to corner. Keep the four smaller triangles separate from the four larger triangles.", checkpoint: "Four accent triangles and four background triangles.", diagram: "cut-pieces" },
      { phase: "Make units", title: "Add the first opposite pair", instruction: "Fold the 6½″ center square and two accent triangles in half to mark their centers. Match and sew one triangle to the top and one to the bottom of the center square.", pressing: "Press the triangles away from the center.", checkpoint: "The triangle centers align with the center-square edges.", diagram: "square-in-square" },
      { phase: "Make units", title: "Complete the first frame", instruction: "Center and sew the remaining accent triangles to the left and right edges. Press outward.", checkpoint: "Inner square-in-square unit measures 9″ raw.", diagram: "square-in-square" },
      { phase: "Make units", title: "Add the background frame", instruction: "Repeat the same opposite-pair sequence with the four larger background triangles: top and bottom first, then left and right.", checkpoint: "All four outer corners are fully covered.", diagram: "square-in-square" },
      { phase: "Check", title: "Square the block", instruction: "Center the 12½″ ruler on the feature square. Trim evenly from all four sides and keep ¼″ beyond each accent point.", checkpoint: "12½″ raw / 12″ finished.", diagram: "final" },
    ],
    precutNote: "The 6½″ center fits easily in a 10″ square. The border triangles need yardage or larger scraps because their starting squares exceed charm size.",
    accuracyNote: "Center every triangle before sewing; trimming only the outside cannot repair an off-center inner square.",
    sources: [{ label: "Polka Dot Chair — 12″ Economy Block photo tutorial", url: "https://www.polkadotchair.com/economy-quilt-block-tutorial/" }],
  },
  {
    slug: "maple-leaf",
    name: "Maple Leaf",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "HST leaf + pieced stem",
    summary: "A nine-patch leaf with four triangle points and a diagonal stem.",
    diagram: "maple-leaf",
    cuts: [feature(["2 — 5″ HST squares", "3 — 4½″ leaf squares", "1 — 1½″ × 7″ stem strip"]), bg(["2 — 5″ HST squares", "1 — 5″ stem square", "1 — 4½″ corner square"])],
    steps: [
      { phase: "Make units", title: "Make four leaf-point HSTs", instruction: "Pair the two 5″ feature squares with two 5″ background squares. Mark, sew ¼″ on both sides, cut, press, and trim the four HSTs to 4½″.", checkpoint: "Four 4½″ HST units.", diagram: "hst-cut" },
      { phase: "Make units", title: "Make the stem unit", instruction: "Cut the remaining 5″ background square once diagonally. Center the 1½″ × 7″ feature strip between the two triangles, sewing one triangle to each long strip edge.", pressing: "Press both seams toward the feature stem.", checkpoint: "Stem runs from one corner to the opposite corner.", diagram: "stem-unit" },
      { phase: "Check", title: "Trim the stem", instruction: "Place the ruler diagonal on the center of the stem strip and trim the unit to 4½″ square.", checkpoint: "Stem unit is exactly 4½″.", diagram: "hst-trim" },
      { phase: "Arrange", title: "Lay out the nine-patch", instruction: "Use the final block map to place three plain leaf squares, four HST leaf points, the stem unit at lower right, and the plain background square at upper left.", checkpoint: "The stem enters the bottom edge and points toward the leaf center.", diagram: "layout" },
      { phase: "Assemble", title: "Sew rows and join", instruction: "Sew three rows. Press alternate rows in opposite directions, nest the row seams, and join.", checkpoint: "12½″ raw / 12″ finished.", diagram: "rows" },
    ],
    precutNote: "Charms work for the HST starts and plain 4½″ patches. Cut the narrow stem strip from yardage or a Jelly Roll subcut trimmed to 1½″.",
    accuracyNote: "The stem unit is deliberately oversized; center the stem before trimming rather than aligning only one raw edge.",
    sources: [{ label: "Polka Dot Chair — 12″ Maple Leaf photo tutorial", url: "https://www.polkadotchair.com/maple-leaf-quilt-block-tutorial/" }],
  },
  {
    slug: "maple-star",
    name: "Maple Star",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Intermediate",
    unitType: "Flying Geese + pieced corners",
    summary: "A compact star built from 2½-inch patches around a 4½-inch center.",
    diagram: "maple-star",
    cuts: [feature(["1 — 4½″ center square (A)"]), accent(["4 — 2½″ × 4½″ center rectangles (B)"]), secondary(["12 — 2½″ star-point and corner squares (C)"]), bg(["8 — 2½″ × 4½″ rectangles", "4 — 2½″ squares"])],
    steps: [
      { phase: "Prepare", title: "Mark eight C squares", instruction: "Draw one diagonal on eight of the twelve 2½″ secondary-color C squares. Reserve the other four C squares for the outer corner units.", checkpoint: "Eight marked C squares; four unmarked C squares.", diagram: "flying-geese-mark" },
      { phase: "Make units", title: "Make four reverse-color Flying Geese", instruction: "Use two marked C squares on each of four background 2½″ × 4½″ rectangles. Sew on the lines, check coverage, trim ¼″ outside, flip, and press. The two small C triangles—not the large background triangle—become the star points.", checkpoint: "Four geese at 2½″ × 4½″ with a large background triangle.", diagram: "flying-geese-unit" },
      { phase: "Make units", title: "Make four corner units", instruction: "Sew one unmarked C square to one background 2½″ square. Add a background 2½″ × 4½″ rectangle to make a 4½″ square. Repeat four times, then rotate each unit so its C square occupies the inner corner of the finished block.", checkpoint: "Four corner units at 4½″ square; each C square is nearest the star.", diagram: "corner-units" },
      { phase: "Make units", title: "Complete the four side units", instruction: "Sew one accent B rectangle to the long edge of each Flying Goose. Rotate each finished side unit so the B rectangle touches center, the large background triangle points toward B, and the two small C triangles point toward the outside edge.", checkpoint: "Four side units at 4½″ square with two visible C star points each.", diagram: "corner-units" },
      { phase: "Arrange", title: "Lay out the 3 × 3 block", instruction: "Place center square A in the middle. Put side units at top, right, bottom, and left with every B rectangle touching A. Put the pieced corner units in the corners with every small C square facing inward.", checkpoint: "Eight C triangles and four C corner squares form the Maple Star shown in the finished map.", diagram: "layout" },
      { phase: "Assemble", title: "Sew rows and join", instruction: "Join three units per row, press for nesting, then sew the three rows together.", checkpoint: "12½″ raw / 12″ finished.", diagram: "rows" },
    ],
    precutNote: "Mini charms supply all C squares and background squares. Jelly Roll strips supply the 2½″ × 4½″ rectangles. Use a charm or layer square for center A.",
    accuracyNote: "Keep fabrics A, B, and C separate: A is only the center, B forms the four rectangles around it, and C forms every star point and inner corner square.",
    sources: [{ label: "Polka Dot Chair — 12″ Maple Star photo tutorial", url: "https://www.polkadotchair.com/maple-star-quilt-block-tutorials/" }],
  },
  {
    slug: "turnstile",
    name: "Turnstile",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Four rotated Flying Geese quadrants",
    summary: "Four Flying Geese units rotate on point around the block center.",
    diagram: "turnstile",
    cuts: [feature(["4 — 3½″ × 6½″ goose bodies"]), accent(["4 — 3½″ × 6½″ contrast rectangles"]), bg(["8 — 3½″ sky squares"])],
    steps: [
      { phase: "Prepare", title: "Mark the sky squares", instruction: "Draw one diagonal line on the wrong side of all eight 3½″ background squares.", checkpoint: "Eight marked sky squares.", diagram: "flying-geese-mark" },
      { phase: "Make units", title: "Make four Flying Geese", instruction: "Use two marked sky squares on each 3½″ × 6½″ feature rectangle. Sew on each line, verify coverage, trim ¼″ beyond the seam, flip, and press.", checkpoint: "Four geese at 3½″ × 6½″.", diagram: "flying-geese-unit" },
      { phase: "Make units", title: "Make four square quadrants", instruction: "Sew one 3½″ × 6½″ accent rectangle to the long edge of each goose. Press toward the accent rectangle.", checkpoint: "Four quadrant units at 6½″ square.", diagram: "quadrants" },
      { phase: "Arrange", title: "Rotate the quadrants", instruction: "Arrange the four 6½″ units in a 2 × 2 grid. Turn each one 90° from the previous unit so the goose points circulate around the center.", checkpoint: "The turnstile has continuous clockwise or counterclockwise motion.", diagram: "layout" },
      { phase: "Assemble", title: "Join the four quadrants", instruction: "Sew two rows, press in opposite directions, nest the center seams, and join the rows.", checkpoint: "12½″ raw / 12″ finished.", diagram: "final" },
    ],
    precutNote: "Layer squares can yield the 3½″ × 6½″ rectangles; charms can supply the 3½″ sky squares after trimming.",
    accuracyNote: "Rotate the completed 6½″ quadrants—not individual goose pieces—before joining.",
    sources: [{ label: "Polka Dot Chair — 12″ Turnstile photo tutorial", url: "https://www.polkadotchair.com/pinwheel-quilt-block-tutorials/" }],
  },
  {
    slug: "bow-tie",
    name: "Bow Tie",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "Stitch-and-flip corners",
    summary: "Four large squares form a bow tie with two small diagonal knot corners.",
    diagram: "bow-tie",
    cuts: [feature(["2 — 6½″ squares", "2 — 3″ knot squares"]), bg(["2 — 6½″ squares"])],
    steps: [
      { phase: "Prepare", title: "Mark the knot squares", instruction: "Draw one diagonal line on the wrong side of both 3″ feature squares.", checkpoint: "Two marked 3″ squares.", diagram: "snowball-corner" },
      { phase: "Make units", title: "Add the knot corners", instruction: "Place one marked square at the inside corner of each 6½″ background square. Sew on the line, verify the flipped corner reaches both raw edges, then trim ¼″ outside and press open.", checkpoint: "Two mirrored snowballed background squares.", diagram: "snowball-corner" },
      { phase: "Arrange", title: "Lay out the four large squares", instruction: "Place the two plain feature squares on one diagonal and the two prepared background squares on the other. The small feature corners must meet at the block center.", checkpoint: "The center forms a small feature square on point.", diagram: "layout" },
      { phase: "Assemble", title: "Join as a Four Patch", instruction: "Sew two rows, press in opposite directions, nest the center seam, and join the rows.", checkpoint: "12½″ raw / 12″ finished.", diagram: "final" },
    ],
    precutNote: "A 10″ square yields a 6½″ patch. The 3″ knot squares can be cut from charms or larger scraps.",
    accuracyNote: "Place both small squares at the two corners that will meet in the block center; mirrored orientation is essential.",
    sources: [{ label: "Polka Dot Chair — 12″ Bow Tie photo tutorial", url: "https://www.polkadotchair.com/bow-tie-quilt-block-tutorial-for-the-block-challenge/" }],
  },
  {
    slug: "pinwheel-star",
    name: "Pinwheel Star",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Intermediate",
    unitType: "Twelve HSTs in a 4 × 4 grid",
    summary: "A feature-fabric pinwheel sits inside an eight-point star formed by the background halves of twelve HSTs.",
    diagram: "pinwheel-star",
    cuts: [feature(["1 — 8¼″ square", "2 — 4″ squares"]), bg(["1 — 8¼″ square", "2 — 4″ squares", "4 — 3½″ corner squares"])],
    steps: [
      { phase: "Prepare", title: "Mark the large HST pair", instruction: "Draw both diagonals to make an X on the wrong side of the 8¼″ feature square. Pair it with the 8¼″ background square, right sides together.", checkpoint: "One aligned large square pair.", diagram: "hst-eight" },
      { phase: "Make units", title: "Make eight HSTs at once", instruction: "Sew a scant ¼″ on both sides of both marked diagonals. Cut through the exact horizontal and vertical centers, then cut on both marked diagonals.", checkpoint: "Eight oversized HST units.", diagram: "hst-eight" },
      { phase: "Make units", title: "Make four more HSTs", instruction: "Pair each 4″ feature square with a 4″ background square. Mark one diagonal, sew ¼″ on both sides, and cut on the line.", checkpoint: "Twelve HST units total.", diagram: "hst-cut" },
      { phase: "Check", title: "Trim all HSTs", instruction: "Press toward the darker fabric and trim every HST to 3½″ using the ruler’s 45° line.", checkpoint: "Twelve 3½″ HSTs plus four plain 3½″ background squares.", diagram: "hst-trim" },
      { phase: "Arrange", title: "Lay out the 4 × 4 star", instruction: "Place plain background squares at the four corners. Use eight HSTs around the outside so their background triangles form the outward star points and their feature triangles face inward. Use the remaining four HSTs for the feature-fabric center pinwheel. Match the final map exactly.", checkpoint: "The feature center pinwheel spins consistently and the four background-color star points face outward.", diagram: "layout" },
      { phase: "Assemble", title: "Sew four rows and join", instruction: "Join four units per row. Press alternate rows in opposite directions, nest all intersections, and sew the four rows together.", checkpoint: "12½″ raw / 12″ finished.", diagram: "rows" },
    ],
    precutNote: "The 8¼″ starts fit inside layer squares. The 4″ starts and 3½″ corners fit inside charms.",
    accuracyNote: "Keep the eight-at-a-time pair perfectly square before the center crosscuts; an off-center cut affects all eight units.",
    sources: [{ label: "Polka Dot Chair — 12″ Pinwheel Star photo tutorial", url: "https://www.polkadotchair.com/learn-how-to-make-a-pinwheel-star-quilt-block-with-our-free-pattern/" }],
  },
  {
    slug: "basket",
    name: "Basket",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Intermediate",
    unitType: "Six HSTs + pieced basket body",
    summary: "A diagonal basket with a contrasting handle corner and stepped body.",
    diagram: "basket",
    cuts: [feature(["2 — 4″ HST squares", "3 — 3½″ basket squares"]), accent(["1 — 4″ HST square"]), bg(["3 — 4″ HST squares", "2 — 3½″ × 6½″ rectangles", "3 needed — 3½″ squares", "Optional: 1 extra 3½″ square as listed in the source"])],
    steps: [
      { phase: "Make units", title: "Make six HSTs", instruction: "Pair two 4″ feature squares with two 4″ background squares to make four HSTs. Pair the 4″ accent square with the remaining 4″ background square to make two more. Press and trim all six to 3½″.", checkpoint: "Four feature/background HSTs and two accent/background HSTs at 3½″.", diagram: "hst-cut" },
      { phase: "Arrange", title: "Lay out the 9½″-wide main section", instruction: "Build four horizontal rows exactly as shown in the finished map. Row 1: background square, then two feature HSTs. Row 2: feature HST, background square, feature square. Row 3: feature HST, then two feature squares. Row 4: one background 3½″ × 6½″ rectangle, then one accent HST.", checkpoint: "The first three rows are 9½″ wide; row 4 is a rectangle plus one HST and is also 9½″ wide.", diagram: "layout" },
      { phase: "Assemble", title: "Sew the main section", instruction: "Sew the pieces within each row. Press neighboring row seams in opposite directions, then join all four rows in order. In the bottom-right accent HST, the accent triangle must touch the unit’s top and left raw edges, exactly as shown in the map.", checkpoint: "Main section measures 9½″ × 12½″ raw.", diagram: "rows" },
      { phase: "Make units", title: "Build the right side column", instruction: "Stack the remaining background 3½″ × 6½″ rectangle at top, the remaining accent HST in the middle, and a 3½″ background square at bottom. Sew the two horizontal seams. In this accent HST, the accent triangle touches the unit’s bottom and left raw edges.", checkpoint: "Side column measures 3½″ × 12½″ raw.", diagram: "corner-units" },
      { phase: "Assemble", title: "Join the two sections", instruction: "Place the 3½″ × 12½″ column on the right side of the 9½″ × 12½″ main section. Match the row intersections and sew the full vertical seam. The two accent triangles meet at their shared corner to form the diagonal handle shown in the source map.", checkpoint: "12½″ raw / 12″ finished.", diagram: "final" },
    ],
    precutNote: "Charms supply every HST start and 3½″ square. Layer squares or yardage are needed for the 3½″ × 6½″ background rectangles.",
    accuracyNote: "Lay out the entire block before joining sections; the two accent HSTs must form one continuous handle direction.",
    sourceNote: "The tutorial’s construction photos and row list verify this exact 12″ map. Its cutting list names four plain 3½″ background squares, but the published assembly uses only three; this guide marks the fourth as an optional spare instead of hiding the mismatch.",
    sources: [{ label: "Polka Dot Chair — 12″ Basket photo tutorial", url: "https://www.polkadotchair.com/twelve-inch-basket-quilt-block-pattern-a-step-by-step-guide/" }],
  },
  {
    slug: "heart",
    name: "Heart",
    family: "modern",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Beginner",
    unitType: "Two mirrored stitch-and-flip halves",
    summary: "A large pieced heart made from two mirrored rectangular halves.",
    diagram: "heart",
    cuts: [feature(["2 — 6½″ × 12½″ heart-half rectangles"]), bg(["4 — 3½″ top-notch squares", "2 — 6½″ bottom-corner squares"])],
    steps: [
      { phase: "Prepare", title: "Mark all six background squares", instruction: "Draw one diagonal line on the wrong side of the four 3½″ squares and the two 6½″ squares.", checkpoint: "Six clearly marked background squares.", diagram: "snowball-corner" },
      { phase: "Make units", title: "Make the left heart half", instruction: "On one 6½″ × 12½″ feature rectangle, place 3½″ squares in both top corners and a 6½″ square at the lower outside corner. Orient the diagonal lines to remove the two top corners and taper the outside lower corner.", details: ["Sew on each line.", "Flip each corner open to confirm coverage before trimming ¼″ outside."], checkpoint: "Left half retains a straight center edge.", diagram: "heart-halves" },
      { phase: "Make units", title: "Make the mirrored right half", instruction: "Repeat on the second rectangle as a mirror image. The large lower square belongs at the opposite outside corner.", checkpoint: "Two mirrored halves make a heart when placed together.", diagram: "heart-halves" },
      { phase: "Arrange", title: "Check the center seam", instruction: "Place both halves side by side. The top notches should mirror and the two lower diagonals should meet at the bottom point.", pressing: "Press the left-half seam allowances one direction and the right-half allowances the opposite direction so matching seams nest.", checkpoint: "The heart shape is continuous before joining.", diagram: "layout" },
      { phase: "Assemble", title: "Join the two halves", instruction: "Nest the matching intersections along the center edge, pin, sew the full 12½″ seam, and press.", checkpoint: "12½″ raw / 12″ finished.", diagram: "final" },
    ],
    precutNote: "Layer squares are too short for the 12½″ heart-half rectangles, so use yardage or fat quarters. Charms can supply the 3½″ top squares; the 6½″ bottom squares fit in layer squares.",
    accuracyNote: "The right half is a true mirror of the left. Check every marked diagonal before trimming away fabric.",
    sources: [{ label: "Polka Dot Chair — Heart blocks in 6″, 9″, and 12″", url: "https://www.polkadotchair.com/simple-heart-quilt-block-tutorial-beginner-friendly-3-sizes/" }],
  },
  {
    slug: "annies-choice",
    name: "Annie’s Choice",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Confident beginner",
    unitType: "Sixteen HSTs in a 4 × 4 grid",
    summary: "A two-color traditional block assembled entirely from rotating HST units.",
    diagram: "annies-choice",
    cuts: [feature(["2 — 8″ squares"]), bg(["2 — 8″ squares"])],
    steps: [
      { phase: "Prepare", title: "Mark two large pairs", instruction: "Draw both diagonals on the wrong side of each 8″ background square. Pair each with one 8″ feature square, right sides together.", checkpoint: "Two aligned 8″ square pairs.", diagram: "hst-eight" },
      { phase: "Make units", title: "Sew around both diagonals", instruction: "Sew a scant ¼″ on both sides of both marked diagonals on each pair. Keep the layers flat and square.", checkpoint: "Four parallel seam lines on each pair.", diagram: "hst-eight" },
      { phase: "Make units", title: "Cut sixteen HSTs", instruction: "Cut each pair through the horizontal and vertical centers, then cut on both marked diagonals. Open and press all units toward the darker fabric.", checkpoint: "Sixteen oversized HSTs.", diagram: "hst-eight" },
      { phase: "Check", title: "Trim every unit", instruction: "Align the ruler’s 45° line with the seam and trim all sixteen HSTs to 3½″ square.", checkpoint: "Sixteen matching 3½″ HSTs.", diagram: "hst-trim" },
      { phase: "Arrange", title: "Follow the 4 × 4 orientation map", instruction: "Lay out all sixteen HSTs exactly as the final block diagram shows. Work one row at a time and compare every triangle corner before sewing.", checkpoint: "Four rows match the Annie’s Choice map.", diagram: "layout" },
      { phase: "Assemble", title: "Sew four rows and join", instruction: "Join four HSTs per row. Press alternate rows in opposite directions, nest intersections, and sew the rows together.", checkpoint: "12½″ raw / 12″ finished.", diagram: "rows" },
    ],
    precutNote: "Both 8″ starting squares fit inside 10″ layer squares. Use two layer squares of each color for one block.",
    accuracyNote: "Orientation creates the named pattern. Keep the complete block map visible while chain-piecing so units are not rotated.",
    sources: [{ label: "Polka Dot Chair — 12″ Annie’s Choice photo tutorial", url: "https://www.polkadotchair.com/annies-choice-12-quilt-block-tutorial/" }],
  },
  {
    slug: "butterfly-cross",
    name: "Butterfly Cross",
    family: "traditional",
    finishedSize: "12″",
    unfinishedSize: "12½″",
    difficulty: "Intermediate",
    unitType: "Eight HSTs + center cross",
    summary: "Four two-color corner units surround a narrow background cross and center square.",
    diagram: "butterfly-cross",
    cuts: [feature(["4 — 3½″ HST squares", "4 — 3″ squares"]), bg(["4 — 3½″ HST squares", "4 — 3″ squares", "4 — 2½″ × 5½″ cross bars"]), accent(["1 — 2½″ center square"])],
    steps: [
      { phase: "Make units", title: "Make eight HSTs", instruction: "Pair each 3½″ feature square with a 3½″ background square. Mark one diagonal, sew ¼″ on both sides, cut, press, and trim all eight HSTs to 3″.", checkpoint: "Eight HSTs at 3″ square.", diagram: "hst-cut" },
      { phase: "Make units", title: "Build four butterfly corners", instruction: "For each corner, join one HST to one 3″ background square and a second HST to one 3″ feature square. Join those two pairs to make a four-patch-style corner unit. Repeat four times.", checkpoint: "Four corner units at 5½″ square.", diagram: "corner-units" },
      { phase: "Assemble", title: "Make the top and bottom sections", instruction: "Sew one butterfly corner unit to each side of a 2½″ × 5½″ background bar. Repeat for the bottom section, rotating the corner units to match the final map.", checkpoint: "Two sections at 5½″ × 12½″.", diagram: "rows" },
      { phase: "Make units", title: "Make the center crossbar", instruction: "Sew one 2½″ × 5½″ background bar to each side of the 2½″ accent center square.", checkpoint: "Center row measures 2½″ × 12½″.", diagram: "corner-units" },
      { phase: "Assemble", title: "Join the three sections", instruction: "Sew the top section, center crossbar, and bottom section together. Match the vertical bar edges so the background cross stays straight.", checkpoint: "12½″ raw / 12″ finished.", diagram: "final" },
    ],
    precutNote: "Charms provide all HST starts and 3″ squares. Cut the four 2½″ × 5½″ bars from yardage or a 2½″ strip.",
    accuracyNote: "Use 3½″—not 3″—starting squares for the HSTs, then trim the sewn units to 3″.",
    sources: [{ label: "Polka Dot Chair — 12″ Butterfly Cross photo tutorial", url: "https://www.polkadotchair.com/how-to-make-a-butterfly-cross-quilt-block/" }],
  },
];

const BLOCK_LIBRARY_ORDER = [
  "sawtooth-star",
  "churn-dash",
  "log-cabin",
  "friendship-star",
  "economy-block",
  "shoo-fly",
  "bear-paw",
  "maple-leaf",
  "maple-star",
  "nine-patch",
  "turnstile",
  "bow-tie",
  "ohio-star",
  "pinwheel-star",
  "basket",
  "heart",
  "rail-fence",
  "annies-choice",
  "butterfly-cross",
] as const;

export const QUILT_BLOCKS: readonly QuiltBlock[] = [
  ...BLOCK_LIBRARY_ORDER.map((slug) => ALL_QUILT_BLOCKS.find((block) => block.slug === slug)).filter((block): block is QuiltBlock => Boolean(block)),
  ...ALL_QUILT_BLOCKS.filter((block) => !BLOCK_LIBRARY_ORDER.includes(block.slug as (typeof BLOCK_LIBRARY_ORDER)[number])),
];

export function getBlock(slug: string) {
  return QUILT_BLOCKS.find((block) => block.slug === slug);
}

export const RESEARCH_SOURCES = [
  {
    title: "Moda — Precut customer guide",
    url: "https://webfiles.modafabrics.com/webfiles/moda-customer-packet.pdf",
    use: "Moda-specific names, nominal sizes, and typical pack counts.",
  },
  {
    title: "Moda — Precut 411",
    url: "https://my.modafabrics.com/inspiration-resources/precut-411",
    use: "Manufacturer and package-count variability.",
  },
  {
    title: "Moda — Jelly, Honey & Accuracy",
    url: "https://modafabrics.com/inspiration-resources/jelly-honey-accuracy",
    use: "Pinked-edge alignment and scant-quarter-inch handling for Moda strips.",
  },
  {
    title: "BERNINA WeAllSew — Accurate Piecing Basics",
    url: "https://weallsew.com/accurate-piecing-basics-quarter-inch-seams/",
    use: "Scant ¼″ explanation and seam-accuracy test.",
  },
  {
    title: "Moda — Half-Triangle Squares Revisited",
    url: "https://my.modafabrics.com/2018/03/tip-jar-half-triangle-squares-revisited",
    use: "Traditional two-at-a-time HST formula.",
  },
  {
    title: "Quilting Daily / OLFA — Eight-at-a-time HSTs",
    url: "https://www.quiltingdaily.com/wp-content/uploads/2018/08/Olfa-Schoolhouse-Steps-Complete.pdf",
    use: "Magic 8 formula and cutting sequence.",
  },
  {
    title: "Moda — Quarter-Square Triangles",
    url: "https://www.modafabrics.com/2018/09/building-blocks-quarter-square-triangles.html",
    use: "QST sizing, yield, and trim-friendly allowance.",
  },
  {
    title: "Moda — Four-from-one Flying Geese",
    url: "https://my.modafabrics.com/2018/09/building-blocks-4-from-1-flying-geese.html",
    use: "No-waste Flying Geese formulas and precut combinations.",
  },
  {
    title: "AllPeopleQuilt — Backing yardage",
    url: "https://www.allpeoplequilt.com/how-to-quilt/finishing/plan-your-quilt-back-and-determine-yardage",
    use: "Backing margin, seams, and orientation planning.",
  },
  {
    title: "Moda — Binding Basics",
    url: "https://my.modafabrics.com/inspiration-resources/binding-basics",
    use: "Usable WOF, strip count, and binding yardage workflow.",
  },
  {
    title: "GE Designs — Stripology® XL CGRGE1XL",
    url: "https://gequiltdesigns.com/products/stripology-xl-ruler-by-ge-designs",
    use: "Creator specifications, capacity, dimensions, and supported cutting jobs for Scott’s slotted ruler.",
  },
  {
    title: "GE Designs — Stripology 101",
    url: "https://gequiltdesigns.com/pages/stripology-101-video-tutorials",
    use: "Creator-led ruler setup, folding, cutting, and subcutting guidance.",
  },
  {
    title: "Creative Grids — 6½″ × 12½″ rectangle CGR612",
    url: "https://www.creativegridsusa.com/products/CGR612",
    use: "Official markings, Turn-a-Round edges, angle lines, and trimming uses for Scott’s bench ruler.",
  },
  {
    title: "Fiskars — 6″ × 24″ sewing ruler 1066148",
    url: "https://www.amazon.com/dp/B0C8BMVL93",
    use: "Exact owned model, dimensions, two-tone grid, and 30°/45°/60° angle guides.",
  },
  {
    title: "Pellon — 820 Quilter’s Grid instructions",
    url: "https://www.pellonprojects.com/wp-content/uploads/2013/02/P00820WHT045010.pdf",
    use: "Manufacturer instructions for testing, arranging, fusing, sewing one direction, clipping, alternating seam allowances, and sewing the second direction.",
  },
  {
    title: "Quiltsmart — PiX Smart Grid instructions",
    url: "https://media.rainpos.com/8837/quiltsmart_grid_instructions_v2.pdf",
    use: "Printed-grid workflow, safe handling, section-size advice, clipping, nesting, and consistent ¼-inch seams.",
  },
  {
    title: "TenSisters — EasyPiecing Grid",
    url: "https://tensisters.com/",
    use: "Manufacturer overview of cut-and-place, fold-and-sew, and pressing on a lightweight fusible foundation.",
  },
  {
    title: "Utah State University Extension — Patchwork Hot Pad",
    url: "https://extension.usu.edu/juab/files/Patchwork_Hot_Pad_Instructions_13.pdf",
    use: "Independent measured example confirming that a 4 × 4 grid of 2½-inch squares becomes an 8½-inch raw panel before edge finishing.",
  },
] as const;

export const QUICK_HST_CHART = [1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 6, 8, 9].map(
  (finished) => [
    finished,
    finished + 0.5,
    hstPlan(finished, 1, "two").trimFriendlyStart,
    hstPlan(finished, 1, "four").trimFriendlyStart,
    hstPlan(finished, 1, "eight").trimFriendlyStart,
  ] as const,
);
