import { formatPrice, type ShopProduct } from "./catalog";

const escape = (value: string) => value.replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]!));

export function orderEmail(products: readonly ShopProduct[], url: string, support: string, paidCents: number) {
  const plural = products.length !== 1;
  const subject = plural ? `Your ${products.length} Monosyth patterns are ready` : `Your ${products[0].name} pattern is ready`;
  const text = `Thank you for your order from Monosyth.\n\nYour ${plural ? "patterns are" : "pattern is"} ready. Download here:\n${url}\n\n${products.map(product => `${product.name} — Edition ${product.version}\n${product.files.map(file => `• ${file.label}`).join("\n")}`).join("\n\n")}\n\nTotal paid: ${formatPrice(paidCents)} USD (including any applicable tax)\n\nThe PDF opens in a regular PDF reader. Electric Quilt 8 is only required for the editable project. These are digital files; nothing is shipped. Keep this private link to return to your downloads.\n\nNeed a hand? Reply to this email or contact ${support}.\n\nMonosyth Labs, LLC\nSmall pieces, wonderful possibilities`;
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(subject)}</title></head>
<body style="margin:0;padding:0;background:#f4f2e9;color:#233d34;font-family:Arial,Helvetica,sans-serif">
<div style="display:none;max-height:0;overflow:hidden;opacity:0">Your next project starts here. Your private download link and ${products.length} ${plural ? "patterns" : "pattern"} are inside.</div>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f4f2e9"><tr><td align="center" style="padding:32px 12px">
<table role="presentation" width="600" cellspacing="0" cellpadding="0" style="width:100%;max-width:600px;border:1px solid #deded2;border-radius:12px;overflow:hidden;background:#fffdf7">
<tr><td style="padding:26px 32px;background:#233d34;color:#fffdf7"><span style="font-size:28px;letter-spacing:-1.3px;font-weight:700">✳ monosyth</span><span style="font-size:10px;letter-spacing:2px;padding-left:16px;color:#dfe5bd">PATTERNS</span></td></tr>
<tr><td style="padding:36px 32px 26px"><p style="margin:0 0 14px;font-size:11px;letter-spacing:2px;color:#677653">PAYMENT RECEIVED</p><h1 style="margin:0 0 16px;font-size:32px;line-height:1.2;letter-spacing:-1px;font-weight:500">Good things are taking shape</h1><p style="margin:0 0 24px;font-size:16px;line-height:1.7;color:#596355">Thank you for choosing Monosyth. Your ${plural ? "patterns are" : "pattern is"} ready for a little fabric and your own imagination.</p>
<table role="presentation" cellspacing="0" cellpadding="0"><tr><td bgcolor="#233d34" style="border-radius:6px"><a href="${escape(url)}" style="display:inline-block;padding:17px 26px;border:1px solid #233d34;border-radius:6px;color:#ffffff;text-decoration:none;font-size:15px;font-weight:700">Download your ${plural ? "patterns" : "pattern"} &nbsp; →</a></td></tr></table>
<p style="font-size:12px;line-height:1.7;color:#697062;margin:16px 0 0">This opens your private download page. Save this email to come back to your files.</p></td></tr>
<tr><td style="padding:0 32px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-top:1px solid #deded2">
${products.map(product => `<tr><td style="padding:22px 0;border-bottom:1px solid #deded2"><h2 style="margin:0 0 5px;font-size:19px;font-weight:600">${escape(product.name)}</h2><p style="margin:0 0 10px;font-size:11px;letter-spacing:1px;color:#697062">EDITION ${escape(product.version)}</p><p style="margin:0;font-size:13px;line-height:1.8;color:#596355">${product.files.map(file => escape(file.label)).join("<br>")}</p></td></tr>`).join("")}
<tr><td style="padding:20px 0;font-size:14px"><strong>Total paid: ${escape(formatPrice(paidCents))} USD</strong><br><span style="font-size:11px;line-height:1.8;color:#697062">Includes any applicable tax · Payment processed by Stripe</span></td></tr></table></td></tr>
<tr><td style="padding:8px 32px 32px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#e8ecdc;border-radius:8px"><tr><td style="padding:20px"><strong style="font-size:14px">A few things before you begin</strong><p style="font-size:13px;line-height:1.8;color:#596355;margin:10px 0 0">Open the PDF in your usual PDF reader. Electric Quilt 8 is only needed for the editable project in the ZIP. These are digital patterns, so nothing is shipped.</p></td></tr></table><p style="font-size:14px;line-height:1.8;margin:24px 0 0">Need a hand? Reply to this email or write to <a href="mailto:${escape(support)}" style="color:#233d34;text-decoration:underline">${escape(support)}</a>.</p><p style="font-size:11px;line-height:1.7;color:#697062;margin:20px 0 0">Button not working? <a href="${escape(url)}" style="color:#233d34;text-decoration:underline">Open your download page here</a>. This link is private to your order; please keep it to yourself.</p></td></tr>
<tr><td style="padding:24px 32px;border-top:1px solid #deded2;font-size:11px;line-height:1.8;color:#697062">Monosyth Labs, LLC<br>Small pieces, wonderful possibilities</td></tr></table>
</td></tr></table></body></html>`;
  return { subject, text, html };
}
